import { TRAINING_ROWS, numberMatches, runEpoch } from '../logic/perceptron.mjs';
import { evaluateSemanticAnswer } from './semantic-answer.mjs';

const SERVER_URL = 'https://script.google.com/macros/s/AKfycby8RWL6uYrKZyoJ6m2GRpWyRmXjwsdskyCiqzKpRhIK5-wrDl-9lWWk8CiAGaVMoy0x/exec';
const STORAGE_KEY = 'informatik11-perzeptron-aufgabe5-v1';
const STEPS = ['discover', 'structure', 'decide', 'learn', 'simulator', 'fast', 'limits', 'summary'];
const epoch = runEpoch();
let active = 'discover';
let selectedTerm = null;
let state = loadState();

const TERMS = [
  ['inputs', 'Eingaben x₁ und x₂'], ['weights', 'Gewichte w₁ und w₂'], ['sum', 'gewichtete Summe a'],
  ['threshold', 'Schwellenwert θ'], ['activation', 'Aktivierungsfunktion'], ['output', 'Ausgabe f(a)'],
];
const TARGETS = [
  ['inputs', 'Merkmalswerte links'], ['weights', 'Zahlen an den Verbindungen'], ['sum', 'Rechenknoten Σ'],
  ['threshold', 'Vergleichsgrenze'], ['activation', 'Vergleichsregel'], ['output', 'Ergebnis 0 oder 1'],
];
const QUIZ = [
  { q:'1. Welche Aussagen zu den Bestandteilen stimmen?', options:[{id:'threshold',text:'Der Schwellenwert legt die Grenze für die Ausgabe fest.',correct:true},{id:'inputs',text:'Die Eingaben beschreiben Merkmale eines Datenpunkts.',correct:true},{id:'output-change',text:'Die Ausgabe verändert Gewichte ohne Zielwert.',correct:false},{id:'weights',text:'Gewichte bestimmen Stärke und Richtung des Einflusses.',correct:true}] },
  { q:'2. Was gilt für x₁ = 2, x₂ = 4, w₁ = −1, w₂ = 2 und θ = 3?', options:[{id:'class',text:'Das Tier wird als ungefährlich klassifiziert.',correct:true},{id:'sum',text:'Die gewichtete Summe ist 6.',correct:true},{id:'output',text:'Die Ausgabe ist 1.',correct:true},{id:'negative',text:'Ein negatives Gewicht erzwingt Ausgabe 0.',correct:false}] },
  { q:'3. Welche Aussagen zur Lernregel stimmen?', options:[{id:'delta',text:'δ = t − f(a).',correct:true},{id:'all-smaller',text:'Bei jedem Datensatz werden beide Gewichte kleiner.',correct:false},{id:'threshold-rule',text:'θ neu = θ alt − δ · α.',correct:true},{id:'zero',text:'Bei δ = 0 bleiben die Parameter unverändert.',correct:true}] },
  { q:'4. Welche Ergebnisse gehören zur ersten Epoche?', options:[{id:'remaining-error',text:'Nach der ersten Epoche bleibt ein Trainingsdatum falsch.',correct:false},{id:'final',text:'Nach vier Schritten gilt w₁ = −3, w₂ = 4 und θ = 1.',correct:true},{id:'step-three',text:'Beim dritten Datensatz ist δ = 0.',correct:true},{id:'step-two',text:'Nach Schritt 2 gilt w₁ = −3, w₂ = 0 und θ = 2.',correct:true}] },
  { q:'5. Was gilt geometrisch?', options:[{id:'normal',text:'Der Gewichtsvektor steht senkrecht auf der Geraden.',correct:true},{id:'line',text:'Die Trenngerade erfüllt w₁x₁ + w₂x₂ = θ.',correct:true},{id:'rate',text:'Eine große Lernrate macht alle Daten trennbar.',correct:false},{id:'linear',text:'Ein Perzeptron trennt nur linear separierbare Daten vollständig.',correct:true}] },
  { q:'6. Was bedeutet Lernen hier?', options:[{id:'compare',text:'Berechnete und erwartete Ausgabe werden verglichen.',correct:true},{id:'goal',text:'Das Perzeptron wählt sein Ziel selbst.',correct:false},{id:'no-consciousness',text:'Dafür sind weder Bewusstsein noch menschliches Verständnis nötig.',correct:true},{id:'algorithm',text:'Ein fester Algorithmus passt Zahlen anhand gelabelter Beispiele an.',correct:true}] },
];
const FIELD_LABELS = {
  product1: 'Beitrag w<sub>1</sub> · x<sub>1</sub>', product2: 'Beitrag w<sub>2</sub> · x<sub>2</sub>', sum: 'gewichtete Summe a', comparison: 'Vergleich a und θ', output: 'Ausgabe f(a)', class: 'Klasse',
  delta: 'Fehler δ', w1: 'w<sub>1</sub> nachher', w2: 'w<sub>2</sub> nachher', threshold: 'θ nachher', endW1: 'Endwert w<sub>1</sub>', endW2: 'Endwert w<sub>2</sub>', theta: 'Endwert θ', steps: 'Trainingsschritte', correctPoints: 'korrekt klassifizierte Trainingspunkte', percent: 'korrekt klassifiziert in Prozent', lineW1: 'Koeffizient vor x<sub>1</sub>', lineW2: 'Koeffizient vor x<sub>2</sub>', line: 'rechte Seite der Geraden',
};

function loadState() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || { epoch: [] }; } catch { return { epoch: [] }; } }
function saveState() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { document.querySelector('#save-status').textContent = 'Der Bearbeitungsstand konnte nicht lokal gespeichert werden.'; } }
function feedback(id, kind, message, html = false) { const el = document.querySelector(`#${id}`); el.hidden = false; el.className = `feedback ${kind}`; if (html) el.innerHTML = message; else el.textContent = message; }
function selectedValues(container) { return [...container.querySelectorAll('input[type=checkbox]:checked')].map((input) => input.value); }
function sameSet(values, expected) { return values.length === expected.length && expected.every((value) => values.includes(value)); }
function showStep(id, focus = false) { if (!STEPS.includes(id)) return; active = id; document.querySelectorAll('[data-panel]').forEach((panel) => { panel.hidden = panel.dataset.panel !== id; }); document.querySelectorAll('[data-tab]').forEach((tab) => { const chosen = tab.dataset.tab === id; tab.setAttribute('aria-selected', String(chosen)); tab.tabIndex = chosen ? 0 : -1; }); state.active = id; saveState(); if (focus) { const heading = document.querySelector(`#${id} h2`); if (heading && !heading.hasAttribute('tabindex')) heading.tabIndex = -1; heading?.scrollIntoView({ behavior:'smooth', block:'start' }); requestAnimationFrame(() => heading?.focus({ preventScroll:true })); } }

function setupTabs() { document.querySelectorAll('[data-tab]').forEach((tab) => { tab.addEventListener('click', () => showStep(tab.dataset.tab, true)); tab.addEventListener('keydown', (event) => { const index = STEPS.indexOf(tab.dataset.tab); const move = {ArrowLeft:-1,ArrowRight:1,ArrowUp:-1,ArrowDown:1}[event.key]; let next = index; if (event.key === 'Home') next = 0; else if (event.key === 'End') next = STEPS.length - 1; else if (move) next = (index + move + STEPS.length) % STEPS.length; else return; event.preventDefault(); showStep(STEPS[next]); document.querySelector(`[data-tab=${STEPS[next]}]`)?.focus(); }); }); document.querySelectorAll('[data-flow]').forEach((container) => { const id = container.dataset.flow; const index = STEPS.indexOf(id); const next = STEPS[index + 1]; const afterNext = STEPS[index + 2]; if (next === 'fast') { container.replaceChildren(flowButton('Weiter zu Grenzen', afterNext), flowButton('Für die Schnellen', next, true)); } else if (next) container.replaceChildren(flowButton(`Weiter: ${labelFor(next)}`, next)); }); showStep(state.active && STEPS.includes(state.active) ? state.active : 'discover'); }
function labelFor(id) { return document.querySelector(`[data-tab=${id}]`)?.textContent.replace(/^\d+\s*/, '') || id; }
function flowButton(text, target, secondary = false) { const button = document.createElement('button'); button.type = 'button'; button.className = secondary ? 'secondary-button' : 'primary-button'; button.textContent = text; button.addEventListener('click', () => showStep(target, true)); return button; }

function setupDiscovery() { const update = () => { const length = document.querySelector('[data-feature=length]').getAttribute('aria-pressed') === 'true' ? 1 : 0; const eyes = document.querySelector('[data-feature=eyes]').getAttribute('aria-pressed') === 'true' ? 1 : 0; const a = -length + 2 * eyes; document.querySelector('#length-value').textContent = length; document.querySelector('#eyes-value').textContent = eyes; document.querySelector('#length-contribution').textContent = length ? '−1' : '0'; document.querySelector('#eyes-contribution').textContent = eyes ? '+2' : '0'; document.querySelector('#wool-sum').textContent = a; document.querySelector('#wool-output').textContent = `Ausgabe ${a >= 1 ? 1 : 0}`; }; document.querySelectorAll('[data-feature]').forEach((button) => button.addEventListener('click', () => { button.setAttribute('aria-pressed', String(button.getAttribute('aria-pressed') !== 'true')); update(); })); document.querySelector('#check-discover').addEventListener('click', () => { const answers = selectedValues(document.querySelector('#discover-options')); if (sameSet(answers, ['path','sign','threshold'])) feedback('discover-feedback','success','Korrekt. Du hast erkannt, wie Merkmalswerte, Verbindungen und Entscheidungsgrenze zusammenwirken.'); else if (answers.some((value) => ['path','sign','threshold'].includes(value))) feedback('discover-feedback','partial','Teilweise korrekt. Prüfe noch Vorzeichen und Entscheidungsgrenze.'); else feedback('discover-feedback','error','Noch nicht korrekt. Aktiviere die Merkmale einzeln und beobachte den Sammelwert.'); }); update(); }

function setupStructure() { const palette = document.querySelector('#term-palette'); const targets = document.querySelector('#term-targets'); TERMS.forEach(([id, text]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'term-button'; button.textContent = text; button.dataset.term = id; button.draggable = true; button.addEventListener('click', () => { selectedTerm = id; palette.querySelectorAll('button').forEach((item) => item.setAttribute('aria-pressed', String(item === button))); }); button.addEventListener('dragstart', (event) => event.dataTransfer.setData('text/plain', id)); palette.append(button); }); TARGETS.forEach(([id,text]) => { const button = document.createElement('button'); button.type='button'; button.className='term-target'; button.dataset.target=id; button.textContent=text; button.addEventListener('click', () => assignTerm(button, selectedTerm)); button.addEventListener('dragover', (event) => event.preventDefault()); button.addEventListener('drop', (event) => { event.preventDefault(); assignTerm(button, event.dataTransfer.getData('text/plain')); }); targets.append(button); }); document.querySelector('#check-structure').addEventListener('click', () => { const buttons = [...targets.children]; let correct = 0; buttons.forEach((target) => { const valid = target.dataset.assigned === target.dataset.target; target.classList.toggle('is-correct', valid); target.classList.toggle('is-wrong', !valid); if (valid) correct++; }); feedback('structure-feedback',correct === 6 ? 'success' : correct ? 'partial':'error',correct === 6 ? 'Korrekt. Alle Bestandteile sind richtig zugeordnet.' : `${correct} von 6 Zuordnungen stimmen. Folge dem Informationsweg von links nach rechts.`); }); }
function assignTerm(target, term) { if (!term) return; target.dataset.assigned = term; const name = TERMS.find(([id]) => id === term)?.[1]; target.textContent = `${target.dataset.target === term ? '✓ ' : ''}${target.dataset.target === term ? name : `${name} → ${TARGETS.find(([id]) => id === target.dataset.target)?.[1]}`}`; target.classList.add('is-selected'); selectedTerm = null; document.querySelectorAll('.term-button').forEach((button) => button.setAttribute('aria-pressed','false')); }

function checkFields(container, expectations) { let correct = 0; const wrong = []; Object.entries(expectations).forEach(([name, expected]) => { const input = container.querySelector(`[data-answer=${name}]`); const valid = typeof expected === 'number' ? numberMatches(input.value, expected, {allowPercent:name === 'percent'}) : input.value === expected; input.classList.toggle('is-correct', valid); input.classList.toggle('is-wrong', !valid); if (valid) correct++; else wrong.push(name); }); return { correct, total:Object.keys(expectations).length, wrong }; }
function fieldFeedback(id, kind, beginning, field) { feedback(id, kind, `${beginning} <strong>${FIELD_LABELS[field] || field}</strong>.`, true); }
function setupDecision() { document.querySelector('#check-decision').addEventListener('click', () => { const result = checkFields(document.querySelector('#decision-form'), {product1:-2,product2:8,sum:6,comparison:'ge',output:'1',class:'safe'}); if (result.correct === result.total) feedback('decision-feedback','success','Korrekt. Die Summe ist 6; das Perzeptron gibt 1 aus und klassifiziert das Tier als ungefährlich.'); else if (result.correct) fieldFeedback('decision-feedback','partial',`${result.correct} von ${result.total} Einträgen stimmen. Prüfe zuerst`,result.wrong[0]); else feedback('decision-feedback','error','Noch nicht korrekt. Berechne zuerst beide Produkte und addiere sie erst danach.'); }); }

function setupEpoch() { const body = document.querySelector('#epoch-body'); epoch.forEach((entry,index) => { const row = document.createElement('tr'); row.dataset.row = index; const before = entry.before; row.innerHTML = `<th scope="row">${index+1}</th><td>${entry.row.x1}</td><td>${entry.row.x2}</td><td>${entry.row.target}</td><td>${before.w1}</td><td>${before.w2}</td><td>${before.threshold}</td>${['sum','output','delta','w1','w2','threshold'].map((name) => `<td><label><span class="sr-only">Schritt ${index+1}: ${FIELD_LABELS[name]}</span>${name === 'output' ? `<select data-field="${name}"><option value="">–</option><option>0</option><option>1</option></select>` : `<input data-field="${name}" inputmode="decimal" autocomplete="off">`}</label></td>`).join('')}<td><button type="button" class="secondary-button check-row">Zeile prüfen</button></td>`; body.append(row); }); body.querySelectorAll('tr').forEach((row,index) => { row.querySelectorAll('input,select,button').forEach((el) => { el.disabled = index > 0; }); row.querySelector('.check-row').addEventListener('click', () => checkEpochRow(index)); }); for (let index = 0; state.epoch?.[index] === true; index++) unlockEpoch(index, true); }
function checkEpochRow(index) { const row = document.querySelector(`#epoch-body tr[data-row="${index}"]`); const entry = epoch[index]; const expect = {sum:entry.sum,output:String(entry.output),delta:entry.delta,w1:entry.w1,w2:entry.w2,threshold:entry.threshold}; let correct=0, first=''; Object.entries(expect).forEach(([field,value]) => { const input=row.querySelector(`[data-field=${field}]`); const valid=typeof value === 'number' ? numberMatches(input.value,value) : input.value === value; input.classList.toggle('is-correct',valid); input.classList.toggle('is-wrong',!valid); if(valid)correct++; else first ||= field; }); if(correct===6){ unlockEpoch(index); feedback('epoch-feedback','success',index === epoch.length - 1 ? 'Korrekt. Nach vier Schritten gilt w₁ = −3, w₂ = 4 und θ = 1. Alle vier Trainingsdaten werden richtig klassifiziert; die Gerade lautet −3x₁ + 4x₂ = 1.' : `Korrekt. Trainingsschritt ${index+1} stimmt; die nächste Zeile ist jetzt freigeschaltet.`); } else if (correct) fieldFeedback('epoch-feedback','partial',`${correct} von 6 Feldern stimmen. Prüfe zuerst`,first); else feedback('epoch-feedback','error','Noch nicht korrekt. Berechne erst a, dann f(a) und δ.'); }
function unlockEpoch(index, restoring = false) { state.epoch ||= []; state.epoch[index] = true; saveState(); const row=document.querySelector(`#epoch-body tr[data-row="${index}"]`); if (restoring && row) { const entry = epoch[index]; const expected = {sum:entry.sum,output:String(entry.output),delta:entry.delta,w1:entry.w1,w2:entry.w2,threshold:entry.threshold}; Object.entries(expected).forEach(([field, value]) => { row.querySelector(`[data-field=${field}]`).value = value; }); } row?.querySelectorAll('input,select').forEach((el)=>el.disabled=true); row?.querySelector('.check-row')?.setAttribute('aria-label', `Trainingsschritt ${index + 1} ist bereits korrekt`); const next=document.querySelector(`#epoch-body tr[data-row="${index+1}"]`); next?.querySelectorAll('input,select,button').forEach((el)=>el.disabled=false); }

function setupSemantic() { const textarea=document.querySelector('#learning-answer'); const counter=document.querySelector('#learning-counter'); const update=()=>counter.textContent=`${textarea.value.length} von 600 Zeichen`; textarea.addEventListener('input',update); update(); document.querySelector('#check-learning-answer').addEventListener('click',async()=>{const answer=textarea.value.trim(); if(answer.length<30){feedback('learning-feedback','error','Bitte formuliere eine etwas ausführlichere Antwort, damit sie sinnvoll ausgewertet werden kann.');textarea.focus();return;} const button=document.querySelector('#check-learning-answer');button.disabled=true;feedback('learning-feedback','', 'Deine Antwort wird mit dem Erwartungshorizont verglichen.');try{const result=await evaluateSemanticAnswer({serverUrl:SERVER_URL,taskId:'11-5-1',answer}); const kind=result.points>=3?'success':result.points?'partial':'error'; feedback('learning-feedback',kind,`${result.points} von ${result.maxPoints} Punkten – ${result.status}. ${(result.feedback||'').trim()}`);}catch(error){feedback('learning-feedback','error',error.message);}finally{button.disabled=false;}}); }
function setupSimulator(){document.querySelector('#check-simulator').addEventListener('click',()=>{const r=checkFields(document.querySelector('#simulator-form'),{endW1:-3,endW2:4,theta:1,steps:4,correctPoints:4,percent:100,lineW1:-3,lineW2:4,line:1});if(r.correct===r.total)feedback('simulator-feedback','success','Korrekt. Nach vier Schritten sind alle vier Trainingspunkte richtig klassifiziert; die Gerade lautet −3x₁ + 4x₂ = 1.');else if(r.correct)fieldFeedback('simulator-feedback','partial',`${r.correct} von ${r.total} Einträgen stimmen. Prüfe zuerst`,r.wrong[0]);else feedback('simulator-feedback','error','Noch nicht korrekt. Prüfe Startwerte, Lernrate 1 und „Iterationen: 1“.');});}
function setupFast(){document.querySelector('#check-fast').addEventListener('click',()=>{const r=checkFields(document.querySelector('#fast-form'),{w1:-1,w2:.5,theta:1.5});feedback('fast-feedback',r.correct===r.total?'success':r.correct?'partial':'error',r.correct===r.total?'Korrekt. Bei α = 0,5 fallen die Parameteränderungen halb so groß aus wie bei α = 1.':r.correct?`${r.correct} von 3 Parametern stimmen. Prüfe das Minuszeichen in der Schwellenwertregel.`:'Noch nicht korrekt. Multipliziere jede Änderung zuerst mit α = 0,5.');});}
function setupLimits(){document.querySelector('#check-limits').addEventListener('click',()=>{const answers=selectedValues(document.querySelector('#limits-options'));if(sameSet(answers,['line','single','continue']))feedback('limits-feedback','success','Korrekt. Die Daten sind nicht linear separierbar; ein einzelnes Perzeptron kann sie nicht fehlerfrei trennen.');else if(answers.some((v)=>['line','single','continue'].includes(v)))feedback('limits-feedback','partial','Teilweise korrekt. Prüfe, ob eine Gerade diagonal liegende gleiche Labels gemeinsam abtrennen kann.');else feedback('limits-feedback','error','Noch nicht korrekt. Zeichne probeweise eine Gerade und kontrolliere alle vier Punkte.');});}
function setupQuiz(){const root=document.querySelector('#quiz-questions');QUIZ.forEach((entry)=>{const box=document.createElement('fieldset');box.className='quiz-question';box.innerHTML=`<legend>${entry.q}</legend>${entry.options.map((option)=>`<label><input type="checkbox" value="${option.id}" data-correct="${option.correct}"> ${option.text}</label>`).join('')}<div class="feedback" role="status" aria-live="polite" hidden></div>`;root.append(box);});document.querySelector('#quiz-form').addEventListener('submit',(event)=>{event.preventDefault();let complete=0;const summary=[];[...root.children].forEach((box,index)=>{const selected=selectedValues(box);const expected=QUIZ[index].options.filter((option)=>option.correct).map((option)=>option.id);const correct=sameSet(selected,expected);if(correct)complete++;const result=box.querySelector('.feedback');result.hidden=false;result.className=`feedback ${correct?'success':'partial'}`;result.textContent=correct?'✓ Richtig. Alle passenden Aussagen sind markiert.':`Noch nicht vollständig. Prüfe besonders die Begriffe aus Frage ${index+1}.`;const answers=QUIZ[index].options.filter((option)=>option.correct).map((option)=>option.text);summary.push(`<li><strong>${QUIZ[index].q}</strong><br>Richtig: ${answers.join(' · ')}</li>`);});document.querySelector('#quiz-progress').textContent=`${complete} von 6 Fragen vollständig richtig`;feedback('quiz-feedback',complete===6?'success':'partial',complete===6?'Alle sechs Fragen sind vollständig richtig beantwortet.':`${complete} von 6 Fragen sind vollständig richtig. Verbessere die markierten Fragen und prüfe erneut.`);const overview=document.querySelector('#quiz-summary');overview.hidden=complete!==6;if(complete===6)overview.innerHTML=`<h3>Quizübersicht</h3><ul>${summary.join('')}</ul>`;});}
function setupReset(){document.querySelector('#reset-progress').addEventListener('click',()=>{if(!confirm('Bearbeitungsstand wirklich zurücksetzen?'))return;try{localStorage.removeItem(STORAGE_KEY);}catch{}location.reload();});}

setupTabs();setupDiscovery();setupStructure();setupDecision();setupEpoch();setupSemantic();setupSimulator();setupFast();setupLimits();setupQuiz();setupReset();
