import { classifyDescriptionResult, compareRelations, explainSqlError, isValidScriptServerUrl, normalizeRelation, parseDelimited, validateSelectStatement } from './sql-lab-core.mjs?v=20260906b';
import { MENU_TABLES, MENU_TABLE_NAMES, MENU_TABLE_SCHEMAS, buildMenuCombinations, menuRelation } from './menue-kreuzprodukt-daten.mjs?v=20260906c';
import { SONG_PLAYLIST_PAIRS, SONG_VERBUND_COLUMN_GROUPS, SONG_VERBUND_COLUMNS, SONG_VERBUND_SQL, SONG_VERBUND_TABLE_NAMES, SONG_VERBUND_TABLE_SCHEMAS, SONG_VERBUND_TABLES, SONG_VERBUND_VISIBLE_TEXT, evaluateFirstConnection, evaluateSecondConnection } from './song-verbund-daten.mjs?v=20260906b';
import { appendSolutionDownloadFromTemplate, focusTabPanelStart, renderTabFlowNavigation, syncTabSemantics } from './tab-navigation.mjs?v=20260906a';

const STORAGE_KEY = 'inf10-sql-grundlagen-v1';
const SCRIPT_SERVER_URL = 'https://script.google.com/macros/s/AKfycby8RWL6uYrKZyoJ6m2GRpWyRmXjwsdskyCiqzKpRhIK5-wrDl-9lWWk8CiAGaVMoy0x/exec';
const NEUTRAL_SQL_PLACEHOLDER = 'SELECT ...\nFROM ...';
const USERS_TABLE_SCHEMAS = Object.freeze([
  Object.freeze({ table: 'users', columns: Object.freeze([
    ['id', 'int'], ['name', 'varchar(255)'], ['username', 'varchar(255)'], ['email', 'varchar(255)'],
    ['email_verified_at', 'date'], ['password', 'varchar(255)'], ['bio', 'varchar(255)'], ['gender', 'varchar(255)'],
    ['birthday', 'date'], ['city', 'varchar(255)'], ['country', 'varchar(255)'], ['centimeters', 'int'],
    ['avatar', 'varchar(255)'], ['role', 'varchar(255)'], ['is_active', 'int'], ['remember_token', 'varchar(255)'],
    ['created_at', 'date'], ['updated_at', 'date']
  ]) })
]);
const state = { tab: 'conditions', answers: {}, feedback: {}, results: {}, server: {} };
const SQL_TABS = [['conditions', 'Bedingungen'], ['fastConditions', 'Für die Schnellen: Bedingungen'], ['aggregates', 'Aggregatfunktionen'], ['fastAggregates', 'Für die Schnellen: Aggregatfunktionen']];

function unlockSolution(event, expectedCode, downloadLinkId, messageId) {
  event.preventDefault();
  const form = event.currentTarget;
  const enteredCode = form.elements['solution-code'].value.toUpperCase().replace(/[^A-Z0-9]/g, '');
  const normalizedExpectedCode = expectedCode.replace(/[^A-Z0-9]/g, '');
  const downloadLink = document.getElementById(downloadLinkId);
  const message = document.getElementById(messageId);

  if (enteredCode === normalizedExpectedCode) {
    downloadLink.hidden = false;
    message.className = 'solution-code-message';
    message.textContent = 'Code korrekt. Das Sicherungsblatt ist freigeschaltet.';
    return;
  }

  downloadLink.hidden = true;
  message.className = 'solution-code-message error';
  message.textContent = 'Der eingegebene Code ist nicht gültig.';
}

window.unlockSolution = unlockSolution;

const tasks = {
  conditions: [
    sql('b2-1', '1', 'Liste die Daten aller Mitglieder auf, bei denen das Geschlecht weiblich ist.', "SELECT *\nFROM users\nWHERE gender = 'female'"),
    sql('b2-2', '2', 'Gib alle Mitglieder aus Deutschland an.', "SELECT *\nFROM users\nWHERE country = 'Deutschland'"),
    describe('b2-3', '3', 'Beschreibe den Zweck dieser Anweisung in eigenen Worten.', "SELECT username, birthday\nFROM users\nWHERE city != 'Berlin';", 'sql-b2-3'),
    sql('b2-4', '4', 'Gib alle Mitglieder aus, die kleiner als 1,80 m sind.', 'SELECT *\nFROM users\nWHERE centimeters < 180'),
    sql('b2-5', '5', 'Korrigiere die Anweisung, damit Namen von Mitgliedern ausgegeben werden, die nicht in Leipzig wohnen.', "SELECT name\nFROM users\nWHERE city != 'Leipzig'", { initialSql: "SELECT namen\nFROM users\nWHERE city = 'Leipzig'", detectMissingNotEqual: true }),
    sql('b2-6', '6', 'Liste alle Frauen aus Leipzig auf.', "SELECT *\nFROM users\nWHERE gender = 'female'\n  AND city = 'Leipzig'", { hints: ['Du brauchst zwei Bedingungen.', 'Verbinde beide Bedingungen mit AND.', 'Vergleiche gender mit female und city mit Leipzig.'] }),
    sql('b2-7', '7', 'Gib die Namen aller Männer über 165 cm und aller Frauen über 160 cm aus.', "SELECT name\nFROM users\nWHERE (gender = 'male' AND centimeters > 165)\n   OR (gender = 'female' AND centimeters > 160)", { hints: ['Es gibt zwei Personengruppen.', 'Verbinde die Gruppen mit OR.', 'Setze die zusammengehörigen Bedingungen jeweils in Klammern.'] }),
    sql('b2-8', '8', 'Finde die Mitglieder, deren Vorname mit B beginnt.', "SELECT *\nFROM users\nWHERE name LIKE 'B%'", { hints: ['Suche nach einem Muster statt nach einem exakten Namen.', 'LIKE vergleicht mit einem Muster.', 'B% bedeutet: beginnt mit B; % steht für beliebig viele weitere Zeichen.'] }),
    sql('b2-9', '9', 'Ermittle, wie viele Mitglieder in München wohnen.', "SELECT COUNT(*) AS anzahl\nFROM users\nWHERE city = 'München'", { hints: ['Wähle zunächst die Mitglieder aus München aus.', 'Zähle die Zeilen der Ergebnisrelation.', 'COUNT(*) fasst die Anzahl der passenden Zeilen zusammen.'] })
  ],
  fastConditions: [
    sql('b2-10', '10', 'Prüfe, ob Mitglieder der Jahrgänge 2005 bis 2010 heute Geburtstag haben.', () => `SELECT *\nFROM users\nWHERE birthday LIKE '%-${todayMonthDay()}'\n  AND birthday BETWEEN '2005-01-01' AND '2010-12-31'`, { birthdayProbe: true, hints: ['Das Datum steht in users im Format YYYY-MM-DD. Vergleiche deshalb nur Monat und Tag.', 'LIKE und % helfen dir, das wechselnde Geburtsjahr vor dem heutigen Monat und Tag zu berücksichtigen.', 'Grenze zusätzlich auf die Jahrgänge 2005 bis 2010 ein.'] }),
    sql('b2-11', '11', 'Finde die Mitglieder, die im März Geburtstag haben.', "SELECT name\nFROM users\nWHERE birthday LIKE '%-03-%'"),
    sql('b2-12', '12', 'Finde alle Berliner, die Marc heißen.', "SELECT *\nFROM users\nWHERE name LIKE 'Marc%'\n  AND city = 'Berlin'"),
    sql('b2-13', '13', 'Ermittle, wie viele Mitglieder Lina oder Lisa heißen.', "SELECT COUNT(*) AS anzahl\nFROM users\nWHERE name LIKE 'Lina%'\n   OR name LIKE 'Lisa%'"),
    sql('b2-14', '14', 'Sortiere alle Männer nach ihrer Körpergröße, die 2008 oder später geboren wurden.', "SELECT *\nFROM users\nWHERE gender = 'male'\n  AND birthday >= '2008-01-01'\nORDER BY centimeters", { compare: { rowOrder: true } }),
    sql('b2-15', '15', 'Gib Geburtsdatum und Benutzernamen aller Frauen aus, die kleiner als 1,60 m sind.', "SELECT birthday, username\nFROM users\nWHERE gender = 'female'\n  AND centimeters < 160", { compare: { columnOrder: false } }),
    sql('b2-16', '16', 'Liste alle Mitglieder auf, die Felix heißen und nicht aus Berlin kommen.', "SELECT *\nFROM users\nWHERE name LIKE 'Felix%'\n  AND city != 'Berlin'"),
    sql('b2-17', '17', 'Erna sucht eine Bekannte aus Berlin, deren Vorname Bea oder Naomi war. Liste alle Daten der möglichen Mitglieder auf.', "SELECT *\nFROM users\nWHERE (name LIKE 'Bea%' OR name LIKE 'Naomi%')\n  AND city = 'Berlin'")
  ],
  aggregates: [
    info(),
    describe('b3-1', '1', 'Beschreibe diese Anweisung in eigenen Worten.', 'SELECT MIN(centimeters) AS kleinste_groesse\nFROM users;', 'sql-b3-1', { info: ['AS benennt die Spalte in der Ergebnisrelation um.', 'Hier heißt die ausgegebene Spalte kleinste_groesse.'] }),
    sql('b3-2', '2', 'Ermittle das Geburtsdatum des jüngsten Mitglieds. Benenne die Spalte juengstes_geburtsdatum.', 'SELECT MAX(birthday) AS juengstes_geburtsdatum\nFROM users', { compare: { columnLabels: true } }),
    selfCheck('b3-3', '3', 'Beschreibe diese Anweisung in eigenen Worten.', 'SELECT *\nFROM users\nORDER BY created_at DESC\nLIMIT 1;', ['ORDER BY created_at DESC sortiert die Registrierung von neu nach alt.', 'LIMIT 1 lässt nur den ersten Datensatz der sortierten Ergebnisrelation übrig.'], { info: ['LIMIT begrenzt die Anzahl der ausgegebenen Zeilen.', 'LIMIT 1 bedeutet: Zeige nach der Sortierung nur den ersten Datensatz.'] })
  ],
  fastAggregates: [
    sql('b3-4', '4', 'Gib die Daten des Mitglieds aus, das sich zuletzt registriert hat.', 'SELECT *\nFROM users\nORDER BY created_at DESC\nLIMIT 1', { compare: { columnLabels: false } }),
    sql('b3-5', '5', 'Ermittle die Größe der größten Nutzerin.', "SELECT MAX(centimeters)\nFROM users\nWHERE gender = 'female'"),
    sql('b3-6', '6', 'Ermittle die durchschnittliche Größe aller Mitglieder aus Dresden.', "SELECT AVG(centimeters)\nFROM users\nWHERE city = 'Dresden'", { compare: { numericTolerance: 0.000001 } }),
    sql('b3-7', '7', 'Ermittle die Anzahl der registrierten Mitglieder aus Berlin.', "SELECT COUNT(*)\nFROM users\nWHERE city = 'Berlin'"),
    sql('b3-8', '8', 'Ermittle die Anzahl der männlichen Mitglieder aus Leipzig.', "SELECT COUNT(*)\nFROM users\nWHERE city = 'Leipzig'\n  AND gender = 'male'")
  ]
};

function sql(id, number, prompt, referenceSql, options = {}) { return { type: 'sql', id, number, prompt, referenceSql, initialSql: options.initialSql || '', detectMissingNotEqual: options.detectMissingNotEqual === true, birthdayProbe: options.birthdayProbe === true, compare: { columnOrder: true, columnLabels: false, rowOrder: false, ...options.compare }, hints: options.hints || [] }; }
function describe(id, number, prompt, statement, serverTaskId, options = {}) { return { type: 'describe', id, number, prompt, statement, serverTaskId, info: options.info || [] }; }
function selfCheck(id, number, prompt, statement, answer, options = {}) { return { type: 'self', id, number, prompt, statement, answer, info: options.info || [] }; }
function info() { return { type: 'info', id: 'aggregate-info' }; }
function todayMonthDay() { const now = new Date(); const offset = now.getTimezoneOffset() * 60000; return new Date(now - offset).toISOString().slice(5, 10); }

class SqlWorker {
  constructor() { this.nextId = 0; this.pending = new Map(); }
  async init(options = { mode: 'users-full' }) {
    this.worker = new Worker(new URL('../../../../include/lib/sql.js/worker.sql-wasm.js', import.meta.url));
    this.worker.onmessage = (event) => { const pending = this.pending.get(event.data.id); if (!pending) return; this.pending.delete(event.data.id); event.data.error ? pending.reject(new Error(event.data.error)) : pending.resolve(event.data); };
    this.worker.onerror = (event) => { this.pending.forEach(({ reject }) => reject(event.error || new Error('SQL-Worker nicht verfügbar.'))); this.pending.clear(); };
    await this.send({ action: 'open' });
    if (options.mode === 'menu-cross-product') {
      const statements = MENU_TABLE_NAMES.flatMap((tableName) => {
        const rows = MENU_TABLES[tableName]; const headers = Object.keys(rows[0]);
        const schema = headers.map((name) => `${quoteIdentifier(name)} ${name === 'preis' ? 'real' : 'varchar(255)'}`).join(', ');
        return [`CREATE TABLE ${quoteIdentifier(tableName)} (${schema})`, ...rows.map((row) => `INSERT INTO ${quoteIdentifier(tableName)} (${headers.map(quoteIdentifier).join(', ')}) VALUES (${headers.map((header) => sqlValue(row[header], header)).join(', ')})`)];
      });
      await this.send({ action: 'exec', sql: statements.join(';') });
      return;
    }
    if (options.mode === 'song-verbund') {
      const schemas = {
        Song: '"id" int PRIMARY KEY, "titel" varchar(255), "genre" varchar(255), "interpret" varchar(255)',
        Song_in_Playlist: '"song_id" int, "playlist_id" int',
        Playlist: '"id" int PRIMARY KEY, "titel" varchar(255)'
      };
      const statements = SONG_VERBUND_TABLE_NAMES.flatMap((tableName) => {
        const rows = SONG_VERBUND_TABLES[tableName]; const headers = Object.keys(rows[0]);
        return [`CREATE TABLE ${quoteIdentifier(tableName)} (${schemas[tableName]})`, ...rows.map((row) => `INSERT INTO ${quoteIdentifier(tableName)} (${headers.map(quoteIdentifier).join(', ')}) VALUES (${headers.map((header) => sqlValue(row[header], header)).join(', ')})`)];
      });
      await this.send({ action: 'exec', sql: statements.join(';') });
      return;
    }
    const response = await fetch('users.csv'); if (!response.ok) throw new Error('users.csv konnte nicht geladen werden.');
    const rows = parseDelimited(await response.text()); const [headers, ...data] = rows;
    const schema = headers.map((name) => `${quoteIdentifier(name)} ${['id', 'centimeters', 'is_active'].includes(name) ? 'INTEGER' : 'TEXT'}`).join(', ');
    const statements = [`CREATE TABLE users (${schema})`];
    data.forEach((row) => statements.push(`INSERT INTO users (${headers.map(quoteIdentifier).join(', ')}) VALUES (${headers.map((header, index) => sqlValue(row[index], header)).join(', ')})`));
    await this.send({ action: 'exec', sql: statements.join(';') });
  }
  send(message) { return new Promise((resolve, reject) => { const id = `sql-${++this.nextId}`; const timeout = window.setTimeout(() => { if (!this.pending.delete(id)) return; reject(new Error('Der SQL-Worker antwortet nicht rechtzeitig.')); }, 15000); this.pending.set(id, { resolve: (value) => { window.clearTimeout(timeout); resolve(value); }, reject: (error) => { window.clearTimeout(timeout); reject(error); } }); try { this.worker.postMessage({ ...message, id }); } catch (error) { window.clearTimeout(timeout); this.pending.delete(id); reject(error); } }); }
  async exec(sqlText) { return normalizeRelation((await this.send({ action: 'exec', sql: sqlText })).results); }
  async execBirthdayProbe(sqlText, monthDay) {
    const probeSql = [
      'SAVEPOINT birthday_probe',
      `UPDATE users SET birthday = '2007-${monthDay}' WHERE id = 1`,
      `UPDATE users SET birthday = '2004-${monthDay}' WHERE id = 2`,
      sqlText,
      'ROLLBACK TO birthday_probe',
      'RELEASE birthday_probe'
    ].join('; ');
    return this.exec(probeSql);
  }
  close() { if (this.worker) { this.send({ action: 'close' }).catch(() => {}); this.worker.terminate(); } }
}
function quoteIdentifier(name) { return `"${String(name).replaceAll('"', '""')}"`; }
function sqlValue(value, header) { if (value === 'NULL' || value === undefined || value === null) return 'NULL'; if (['id', 'centimeters', 'is_active', 'preis', 'song_id', 'playlist_id'].includes(header) && /^-?\d+(?:\.\d+)?$/.test(value)) return value; return `'${String(value).replaceAll("'", "''")}'`; }

let database;
let databaseReady = false;
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function restore() { try { Object.assign(state, JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}')); } catch { /* Speicherstand ist optional. */ } }
function element(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }

function activateSqlTab(id, { focusContent = false } = {}) { state.tab = id; save(); render({ focusContent }); }
function render({ focusContent = false } = {}) {
  const tabs = document.getElementById('sql-tabs'); tabs.replaceChildren();
  SQL_TABS.forEach(([id, label], index) => { const button = element('button', 'step-tab', label); button.type = 'button'; button.id = `tab-${id}`; button.dataset.tab = id; button.role = 'tab'; button.ariaSelected = String(state.tab === id); button.tabIndex = state.tab === id ? 0 : -1; button.setAttribute('aria-controls', 'sql-panel'); button.addEventListener('click', () => activateSqlTab(id)); button.addEventListener('keydown', (event) => moveTabFocus(event, SQL_TABS, index)); tabs.append(button); });
  const panel = document.getElementById('sql-panel'); panel.replaceChildren();
  panel.setAttribute('aria-labelledby', `tab-${state.tab}`);
  panel.append(schemaCard(USERS_TABLE_SCHEMAS));
  const heading = element('div', 'step-heading'); heading.append(element('span', 'step-number', '5')); const title = element('div'); title.append(element('p', 'step-kicker', state.tab.startsWith('fast') ? 'Vertiefen' : 'Wiederholen'), element('h2', '', SQL_TABS.find(([id]) => id === state.tab)[1])); heading.append(title); panel.append(heading);
  tasks[state.tab].forEach((task) => panel.append(renderTask(task)));
  if (state.tab === 'fastAggregates') appendSolutionDownloadFromTemplate(panel);
  renderTabFlowNavigation(panel, { items: SQL_TABS.map(([id, label]) => ({ id, label })), currentId: state.tab, onNavigate: activateSqlTab });
  syncTabSemantics(tabs, state.tab);
  if (focusContent) focusTabPanelStart(panel);
}

function moveTabFocus(event, labels, index) {
  const keys = { ArrowLeft: -1, ArrowUp: -1, ArrowRight: 1, ArrowDown: 1 };
  let nextIndex;
  if (event.key === 'Home') nextIndex = 0;
  else if (event.key === 'End') nextIndex = labels.length - 1;
  else if (keys[event.key]) nextIndex = (index + keys[event.key] + labels.length) % labels.length;
  else return;
  event.preventDefault();
  document.getElementById(`tab-${labels[nextIndex][0]}`)?.click();
  document.getElementById(`tab-${labels[nextIndex][0]}`)?.focus();
}

function schemaCard(schemas) {
  const card = element('aside', 'scenario-card accent sql-schema-card'); card.setAttribute('aria-label', 'Tabellenschema der SQL-Übungsdaten');
  card.append(element('strong', 'schema-title', schemas.length === 1 ? 'Tabellenschema' : 'Tabellenschemata'));
  const scroll = element('div', 'schema-scroll'); scroll.tabIndex = 0; scroll.setAttribute('aria-label', 'Tabellenschemata horizontal scrollen');
  schemas.forEach(({ table, columns }) => { const code = element('code', 'schema-code', `${table} (${columns.map(([name, type]) => `${name}: ${type}`).join(', ')})`); scroll.append(code); });
  card.append(scroll); return card;
}
function renderTask(task) {
  if (task.type === 'info') return aggregateInfo();
  const card = element('section', 'task-card sql-task'); card.id = `task-${task.id}`; card.append(element('h3', '', `Aufgabe ${task.number}`), element('p', '', task.prompt));
  if (task.statement) { const statement = element('pre', 'given-sql'); statement.textContent = task.statement; card.append(statement); }
  if (task.info?.length) { const details = element('details', 'sql-info'); details.append(element('summary', '', 'Infobox')); task.info.forEach((line) => details.append(element('p', '', line))); card.append(details); }
  if (task.type === 'sql') renderSqlTask(card, task); else if (task.type === 'describe') renderDescribeTask(card, task); else renderSelfCheck(card, task);
  return card;
}
function aggregateInfo() {
  const card = element('section', 'scenario-card aggregate-intro'); card.append(element('h3', '', 'Kurz erklärt: Aggregatfunktionen'));
  card.append(element('p', '', 'Eine Aggregatfunktion verarbeitet mehrere Werte und gibt einen zusammengefassten Wert zurück.')); const code = element('pre', 'given-sql'); code.textContent = 'SELECT COUNT(*) AS anzahl\nFROM users'; card.append(code);
  const list = element('dl', 'aggregate-list'); [['COUNT(attribut) / COUNT(*)', 'Anzahl der Datensätze'], ['MIN(attribut)', 'kleinster Wert'], ['MAX(attribut)', 'größter Wert'], ['AVG(attribut)', 'arithmetischer Mittelwert'], ['SUM(attribut)', 'Summe'], ['AS', 'benennt eine Ergebnisspalte um']].forEach(([term, meaning]) => { list.append(element('dt', '', term), element('dd', '', meaning)); }); card.append(list); return card;
}
function renderSqlTask(card, task) {
  const label = element('label', 'sql-label', 'Deine vollständige SQL-Anweisung'); label.htmlFor = `input-${task.id}`; const input = document.createElement('textarea'); input.id = label.htmlFor; input.className = 'sql-input'; input.spellcheck = false; input.placeholder = NEUTRAL_SQL_PLACEHOLDER; const hasSavedAnswer = Object.prototype.hasOwnProperty.call(state.answers, task.id); input.value = hasSavedAnswer ? state.answers[task.id] : task.initialSql; if (!hasSavedAnswer && task.initialSql) { state.answers[task.id] = task.initialSql; save(); } input.addEventListener('input', () => { state.answers[task.id] = input.value; delete state.feedback[task.id]; delete state.results[task.id]; save(); renderTaskFeedback(task, card); }); input.addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') { event.preventDefault(); runTask(task, card); } }); card.append(label, input);
  appendHints(card, task.hints); const actions = element('div', 'action-row'); const run = element('button', 'primary-button', 'Anfrage ausführen'); run.type = 'button'; run.disabled = !databaseReady; run.addEventListener('click', () => runTask(task, card, input, run)); actions.append(run); if (task.initialSql) { const reset = element('button', 'secondary-button', 'Ursprungsanweisung wiederherstellen'); reset.type = 'button'; reset.addEventListener('click', () => { input.value = task.initialSql; state.answers[task.id] = task.initialSql; delete state.feedback[task.id]; delete state.results[task.id]; save(); renderTaskFeedback(task, card); input.focus(); }); actions.append(reset); } actions.append(element('span', 'shortcut-hint', 'Strg/Cmd + Enter')); card.append(actions); renderTaskFeedback(task, card);
}
function appendHints(card, hints) { if (!hints.length) return; const box = element('div', 'help-stack'); hints.forEach((hint, index) => { const details = element('details'); details.append(element('summary', '', `Hilfe ${index + 1}`), element('p', '', hint)); box.append(details); }); card.append(box); }
async function runTask(task, card, input = card.querySelector('.sql-input'), button = card.querySelector('.primary-button')) {
  const sqlText = state.answers[task.id] || ''; const check = validateSelectStatement(sqlText);
  if (!check.ok) { state.feedback[task.id] = { level: 'hint', text: check.message }; save(); renderTaskFeedback(task, card); return; }
  if (task.detectMissingNotEqual && /\bwhere\s+city\s*=\s*'Leipzig'/i.test(sqlText)) { state.feedback[task.id] = { level: 'hint', text: "Noch nicht korrekt: Für ‚nicht in Leipzig‘ fehlt im Vergleichsoperator das Ausrufezeichen: !=." }; save(); renderTaskFeedback(task, card); return; }
  if (!databaseReady) { state.feedback[task.id] = { level: 'hint', text: 'Warte bitte, bis die Tabelle users vollständig geladen ist.' }; renderTaskFeedback(task, card); return; }
  input.disabled = true; button.disabled = true; delete state.results[task.id]; state.feedback[task.id] = { level: 'hint', text: 'Die Anfrage wird ausgeführt …' }; renderTaskFeedback(task, card);
  try {
    const referenceSql = typeof task.referenceSql === 'function' ? task.referenceSql() : task.referenceSql;
    const actual = await database.exec(check.sql); const reference = await database.exec(referenceSql); let comparison = compareRelations(actual, reference, task.compare);
    if (comparison.correct && task.birthdayProbe) {
      const monthDay = todayMonthDay();
      const probeActual = await database.execBirthdayProbe(check.sql, monthDay);
      const probeReference = await database.execBirthdayProbe(referenceSql, monthDay);
      comparison = compareRelations(probeActual, probeReference, task.compare);
      if (!comparison.correct) comparison = { correct: false, level: 'partial', reason: 'Berücksichtige beim heutigen Geburtstag Monat und Tag sowie die Jahrgänge 2005 bis 2010.' };
    }
    if (comparison.correct) { state.feedback[task.id] = { level: 'success', text: actual.values.length ? 'Korrekt: Deine Abfrage liefert die erwartete Ergebnisrelation.' : 'Korrekt: Für heute gibt es keine passenden Datensätze.' }; state.results[task.id] = actual; }
    else { state.feedback[task.id] = { level: comparison.level, text: `${comparison.level === 'partial' ? 'Teilweise korrekt' : 'Noch nicht korrekt'}: ${comparison.reason}` }; delete state.results[task.id]; }
  } catch (error) { state.feedback[task.id] = { level: 'error', text: `SQL-Fehler: ${explainSqlError(error)}` }; delete state.results[task.id]; }
  input.disabled = false; button.disabled = false; save(); renderTaskFeedback(task, card);
}
function renderDescribeTask(card, task) {
  const label = element('label', 'sql-label', 'Deine Erklärung'); label.htmlFor = `input-${task.id}`; const input = document.createElement('textarea'); input.id = label.htmlFor; input.className = 'description-input'; input.maxLength = 1200; input.value = state.answers[task.id] || ''; input.addEventListener('input', () => { state.answers[task.id] = input.value; delete state.server[task.id]; save(); renderServerFeedback(task, card); }); card.append(label, input); const actions = element('div', 'action-row'); const button = element('button', 'primary-button', 'Erklärung prüfen'); button.type = 'button'; button.addEventListener('click', () => submitDescription(task, input, card)); actions.append(button); card.append(actions); renderServerFeedback(task, card);
}
function renderSelfCheck(card, task) { const label = element('label', 'sql-label', 'Deine Erklärung'); label.htmlFor = `input-${task.id}`; const input = document.createElement('textarea'); input.id = label.htmlFor; input.className = 'description-input'; input.value = state.answers[task.id] || ''; input.addEventListener('input', () => { state.answers[task.id] = input.value; save(); }); card.append(label, input); const details = element('details', 'sql-info'); details.append(element('summary', '', 'Selbstkontrolle anzeigen')); task.answer.forEach((line) => details.append(element('p', '', line))); card.append(details); }
function renderTaskFeedback(task, card) { card.querySelectorAll('.sql-feedback, .result-relation').forEach((node) => node.remove()); const feedback = state.feedback[task.id]; if (feedback) { const box = element('p', `feedback ${feedback.level} sql-feedback`, feedback.text); box.setAttribute('aria-live', 'polite'); card.append(box); } if (state.results[task.id]) card.append(renderRelation(state.results[task.id])); }
function renderRelation(relation, options = {}) { const columns = options.columns || relation.columns; const formatValue = options.formatValue || ((value) => value === null ? 'NULL' : String(value)); const shell = element('section', `table-shell result-relation${options.columnGroups?.length ? ' has-column-groups' : ''}`); shell.setAttribute('aria-label', options.label || 'Ergebnisrelation der SQL-Anfrage'); shell.setAttribute('aria-live', 'polite'); const caption = element('div', 'table-caption'); caption.append(element('strong', '', options.title || 'Ergebnisrelation'), element('span', '', relation.values.length > 100 ? `100 von ${relation.values.length} Zeilen angezeigt` : `${relation.values.length} Zeile(n)`)); shell.append(caption); if (!relation.values.length) { shell.append(element('p', 'empty-result', 'Die Abfrage ist gültig, liefert aber keine Datensätze.')); return shell; } const scroll = element('div', 'table-scroll'); scroll.tabIndex = 0; scroll.setAttribute('aria-label', 'Ergebnisrelation horizontal und vertikal scrollen'); const table = element('table', `data-table${columns.length <= 3 ? ' compact' : ''}`); const cap = element('caption', 'visually-hidden', options.caption || 'Ergebnis deiner SQL-Abfrage'); table.append(cap); const head = document.createElement('thead'); if (options.columnGroups?.length) { options.columnGroups.forEach(({ columns: groupColumns }) => { const group = document.createElement('colgroup'); group.span = groupColumns.length; table.append(group); }); const groupRow = document.createElement('tr'); options.columnGroups.forEach(({ table: tableName, columns: groupColumns }) => { const th = element('th', 'relation-group-heading', tableName); th.colSpan = groupColumns.length; th.scope = 'colgroup'; groupRow.append(th); }); head.append(groupRow); } const row = document.createElement('tr'); columns.forEach((column) => { const th = element('th', '', column); th.scope = 'col'; row.append(th); }); head.append(row); const body = document.createElement('tbody'); relation.values.slice(0, 100).forEach((values) => { const tr = document.createElement('tr'); values.forEach((value, index) => tr.append(element('td', '', formatValue(value, index)))); body.append(tr); }); table.append(head, body); scroll.append(table); shell.append(scroll); return shell; }

function submitDescription(task, input, card) {
  const answer = input.value.trim(); if (answer.length < 10) { state.server[task.id] = { level: 'error', text: 'Bitte formuliere eine etwas ausführlichere Antwort.' }; save(); renderServerFeedback(task, card); input.focus(); return; }
  if (!isValidScriptServerUrl(SCRIPT_SERVER_URL)) { state.server[task.id] = { level: 'error', text: 'Der Auswertungsserver ist nicht korrekt eingerichtet.' }; save(); renderServerFeedback(task, card); return; }
  const button = card.querySelector('.primary-button'); button.disabled = true; input.disabled = true; button.textContent = 'Erklärung wird geprüft …'; state.server[task.id] = { level: 'loading', text: 'Deine Erklärung wird ausgewertet.' }; renderServerFeedback(task, card);
  const requestId = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`; const url = new URL(SCRIPT_SERVER_URL); url.searchParams.set('callback', '__handleSqlDescriptionResult'); url.searchParams.set('requestId', requestId); url.searchParams.set('taskId', task.serverTaskId); url.searchParams.set('answer', answer);
  if (url.toString().length > 1800) { input.disabled = false; button.disabled = false; button.textContent = 'Erklärung prüfen'; state.server[task.id] = { level: 'error', text: 'Deine Erklärung ist für die automatische Übertragung zu lang. Bitte kürze sie etwas.' }; save(); renderServerFeedback(task, card); return; }
  const script = document.createElement('script'); const timeout = window.setTimeout(() => finishDescription(requestId, task, card, { ok: false, message: 'Der Auswertungsserver hat nicht rechtzeitig geantwortet.' }), 60000); pendingDescriptions.set(requestId, { task, card, input, button, script, timeout }); script.src = url; script.async = true; script.onerror = () => finishDescription(requestId, task, card, { ok: false, message: 'Der Auswertungsserver konnte nicht geladen werden.' }); document.body.append(script);
}
const pendingDescriptions = new Map();
window.__handleSqlDescriptionResult = (message) => { if (message?.type && message.type !== 'GEMINI_EVALUATION_RESULT') return; const pending = pendingDescriptions.get(message?.requestId); if (pending) finishDescription(message.requestId, pending.task, pending.card, message.result); };
function finishDescription(requestId, task, card, result) { const pending = pendingDescriptions.get(requestId); if (!pending) return; clearTimeout(pending.timeout); pending.script.remove(); pending.input.disabled = false; pending.button.disabled = false; pending.button.textContent = 'Erklärung erneut prüfen'; pendingDescriptions.delete(requestId); state.server[task.id] = classifyDescriptionResult(result); save(); renderServerFeedback(task, card); }
function appendEvaluationList(container, headingText, items, emptyText) { container.append(element('h4', '', headingText)); const list = document.createElement('ul'); (items.length ? items : [emptyText]).forEach((item) => list.append(element('li', '', item))); container.append(list); }
function renderServerFeedback(task, card) {
  card.querySelector('.server-feedback')?.remove(); const feedback = state.server[task.id]; if (!feedback) return;
  const box = element('section', `result server-feedback${feedback.level === 'loading' ? '' : ` ${feedback.level}`}`); box.setAttribute('aria-live', 'polite');
  if (Number.isFinite(feedback.points) && feedback.maxPoints > 0) {
    box.append(element('h3', '', `${feedback.points} von ${feedback.maxPoints} Punkten – ${feedback.status}`));
    appendEvaluationList(box, 'Das ist dir gelungen:', feedback.strengths, 'Es wurde noch kein eindeutiger richtiger Aspekt erkannt.');
    appendEvaluationList(box, 'Das solltest du ergänzen oder überprüfen:', feedback.missing, 'Es fehlen keine wesentlichen Aspekte.');
    const detail = element('div', 'feedback'); detail.append(element('h4', '', 'Rückmeldung'), element('p', '', feedback.text)); box.append(detail);
  } else box.append(element('p', '', feedback.text));
  card.append(box);
}

// Aufgabe 6 verwendet dieselbe Worker-Ausführung und Validierung wie Aufgabe 5.
const MENU_STORAGE_KEY = 'inf10-kreuzprodukt-mensa-v1';
const MENU_TABS = [['menus', 'Menüs kombinieren'], ['sql', 'Kreuzprodukt mit SQL'], ['filter', 'Mit Bedingung einschränken'], ['summary', 'Zusammenfassung']];
const menuState = { tab: 'menus', prediction: '', menusVisible: false, answers: {}, feedback: {}, results: {}, selfCheck: {} };
const menuReferenceSql = 'SELECT *\nFROM Vorspeise, Hauptspeise, Nachspeise';
const formatEuro = (value, index) => index % 2 === 1 && typeof value === 'number' ? `${value.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €` : String(value);
function saveMenuState() { localStorage.setItem(MENU_STORAGE_KEY, JSON.stringify(menuState)); }
function restoreMenuState() { try { Object.assign(menuState, JSON.parse(localStorage.getItem(MENU_STORAGE_KEY) || '{}')); } catch { /* Speicherstand ist optional. */ } }
function menuFeedback(id, level, text) { menuState.feedback[id] = { level, text }; saveMenuState(); }
function activateMenuTab(id, { focusContent = false } = {}) { menuState.tab = id; saveMenuState(); renderMenuModule({ focusContent }); }
function renderMenuModule({ focusContent = false } = {}) {
  const tabs = document.getElementById('menu-tabs'); tabs.replaceChildren();
  MENU_TABS.forEach(([id, label], index) => { const button = element('button', 'step-tab', label); button.type = 'button'; button.id = `tab-${id}`; button.dataset.tab = id; button.role = 'tab'; button.ariaSelected = String(menuState.tab === id); button.tabIndex = menuState.tab === id ? 0 : -1; button.setAttribute('aria-controls', 'menu-panel'); button.addEventListener('click', () => activateMenuTab(id)); button.addEventListener('keydown', (event) => moveTabFocus(event, MENU_TABS, index)); tabs.append(button); });
  const panel = document.getElementById('menu-panel'); panel.replaceChildren(); panel.setAttribute('aria-labelledby', `tab-${menuState.tab}`);
  panel.append(schemaCard(MENU_TABLE_SCHEMAS));
  if (menuState.tab === 'menus') renderMenuDiscovery(panel);
  if (menuState.tab === 'sql') renderMenuSql(panel);
  if (menuState.tab === 'filter') renderMenuFilter(panel);
  if (menuState.tab === 'summary') renderMenuSummary(panel);
  if (menuState.tab === 'summary') appendSolutionDownloadFromTemplate(panel);
  renderTabFlowNavigation(panel, { items: MENU_TABS.map(([id, label]) => ({ id, label })), currentId: menuState.tab, onNavigate: activateMenuTab });
  syncTabSemantics(tabs, menuState.tab);
  if (focusContent) focusTabPanelStart(panel);
}
function menuHeading(number, kicker, title) { const heading = element('div', 'step-heading'); heading.append(element('span', 'step-number', String(number))); const copy = element('div'); copy.append(element('p', 'step-kicker', kicker), element('h2', '', title)); heading.append(copy); return heading; }
function renderMenuDiscovery(panel) {
  panel.append(menuHeading(1, 'Entdecken', 'Wie entstehen vollständige Menüs?'));
  const scenario = element('section', 'scenario-card accent'); scenario.append(element('h3', '', 'Die Mensa stellt drei Gänge zusammen.'), element('p', '', 'Wähle jeweils eine Vorspeise, eine Hauptspeise und eine Nachspeise. Schau zuerst auf die drei Ausgangsrelationen.')); scenario.append(renderMenuSourceTables()); panel.append(scenario);
  const task = element('section', 'task-card sql-task'); task.append(element('h3', '', 'Vorhersage'), element('p', '', 'Wie viele verschiedene vollständige Menüs sind möglich?')); const label = element('label', 'sql-label', 'Anzahl der Menüs'); label.htmlFor = 'menu-prediction'; const input = document.createElement('input'); input.id = label.htmlFor; input.className = 'menu-number-input'; input.type = 'number'; input.min = '0'; input.inputMode = 'numeric'; input.value = menuState.prediction; input.addEventListener('input', () => { menuState.prediction = input.value; delete menuState.feedback.prediction; saveMenuState(); renderMenuFeedback(task, 'prediction'); }); const button = element('button', 'primary-button', 'Anzahl prüfen'); button.type = 'button'; button.addEventListener('click', () => { if (Number(menuState.prediction) === 12) menuFeedback('prediction', 'success', 'Korrekt: 4 Vorspeisen · 3 Hauptspeisen · 1 Nachspeise ergeben 12 Menüs.'); else menuFeedback('prediction', 'hint', 'Noch nicht korrekt. Kombiniere systematisch: Multipliziere die Anzahl der möglichen Vorspeisen, Hauptspeisen und Nachspeisen.'); renderMenuFeedback(task, 'prediction'); }); task.append(label, input, button); renderMenuFeedback(task, 'prediction'); panel.append(task);
  const generate = element('section', 'task-card'); generate.append(element('h3', '', 'Alle Kombinationen sichtbar machen'), element('p', '', 'Erzeuge die Ergebnisrelation. Jede Zeile enthält genau eine Auswahl aus jeder der drei Tabellen.')); const action = element('button', 'primary-button', menuState.menusVisible ? 'Ergebnisrelation anzeigen' : 'Alle Menüs erzeugen'); action.type = 'button'; action.addEventListener('click', () => { menuState.menusVisible = true; saveMenuState(); renderMenuModule(); }); generate.append(action); if (menuState.menusVisible) generate.append(renderMenuResult(menuRelation(buildMenuCombinations()), 'Ergebnisrelation: alle Menüs')); panel.append(generate);
}
function renderMenuSourceTables() { const wrapper = element('div', 'menu-source-tables'); MENU_TABLE_NAMES.forEach((tableName) => { const relation = MENU_TABLES[tableName]; const section = element('section', 'table-shell menu-source-table'); const table = document.createElement('table'); const caption = element('caption', '', tableName); table.append(caption); const head = document.createElement('thead'); const tr = document.createElement('tr'); ['name', 'preis'].forEach((name) => { const th = element('th', '', name); th.scope = 'col'; tr.append(th); }); head.append(tr); const body = document.createElement('tbody'); relation.forEach((row) => { const line = document.createElement('tr'); line.append(element('td', '', row.name), element('td', '', `${row.preis.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`)); body.append(line); }); table.append(head, body); section.append(table); wrapper.append(section); }); return wrapper; }
function renderMenuResult(relation, title) { const shell = renderRelation(relation, { title, caption: title, columns: menuRelation().columns, columnGroups: MENU_TABLE_SCHEMAS.map(({ table, columns }) => ({ table, columns: columns.map(([name]) => name) })), formatValue: formatEuro }); shell.classList.add('menu-result'); return shell; }
function renderMenuSql(panel) {
  panel.append(menuHeading(2, 'Verstehen und anwenden', 'Das Kreuzprodukt mit SQL'));
  const intro = element('section', 'scenario-card accent'); intro.append(element('p', '', 'Die SQL-Anweisung verbindet jeden Datensatz einer Tabelle mit jedem Datensatz aller weiteren Tabellen.'), codeBlock('SELECT *\nFROM Vorspeise, Hauptspeise, Nachspeise;')); const list = element('ul'); ['SELECT * wählt alle Spalten aus.', 'In FROM stehen hier drei Tabellen, durch Kommata getrennt.', 'Dadurch entstehen alle möglichen Kombinationen.'].forEach((line) => list.append(element('li', '', line))); intro.append(list); panel.append(intro);
  const task = element('section', 'task-card sql-task'); task.append(element('h3', '', 'Vervollständige die Abfrage'), element('p', '', 'Formuliere eine vollständige SELECT-Abfrage für alle Menükombinationen.')); renderMenuSqlInput(task, 'cross-product', menuReferenceSql, { success: 'Korrekt: Die Abfrage erzeugt alle 12 Menükombinationen.' }); panel.append(task);
  const fact = element('section', 'short-summary menu-memory'); fact.append(element('h2', '', 'Merksatz'), element('p', '', 'Wenn bei einer SELECT-Abfrage beim Schlüsselwort FROM mehrere Tabellen angegeben werden, wird das Kreuzprodukt auf diesen Tabellen angewendet.\nBeim Kreuzprodukt wird jeder Datensatz der einen Tabelle mit jedem Datensatz der anderen Tabelle (bzw. den Datensätzen aller weiteren Tabellen) verknüpft.')); panel.append(fact);
}
function codeBlock(text) { const pre = element('pre', 'given-sql'); pre.textContent = text; return pre; }
function renderMenuSqlInput(card, id, referenceSql, options = {}) { const label = element('label', 'sql-label', 'Deine vollständige SQL-Anweisung'); label.htmlFor = `menu-input-${id}`; const input = document.createElement('textarea'); input.id = label.htmlFor; input.className = 'sql-input'; input.spellcheck = false; input.placeholder = NEUTRAL_SQL_PLACEHOLDER; input.value = menuState.answers[id] || ''; input.addEventListener('input', () => { menuState.answers[id] = input.value; delete menuState.feedback[id]; delete menuState.results[id]; saveMenuState(); renderMenuFeedback(card, id); }); input.addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') { event.preventDefault(); runMenuSql(id, referenceSql, card, options); } }); card.append(label, input); if (options.hints) appendHints(card, options.hints); const actions = element('div', 'action-row'); const button = element('button', 'primary-button', 'Anfrage ausführen'); button.type = 'button'; button.disabled = !databaseReady; button.addEventListener('click', () => runMenuSql(id, referenceSql, card, options)); actions.append(button, element('span', 'shortcut-hint', 'Strg/Cmd + Enter')); card.append(actions); renderMenuFeedback(card, id); }
async function runMenuSql(id, referenceSql, card, options = {}) { const sqlText = menuState.answers[id] || ''; const check = validateSelectStatement(sqlText); if (!check.ok) { menuFeedback(id, 'hint', check.message); renderMenuFeedback(card, id); return; } if (!databaseReady) { menuFeedback(id, 'hint', 'Warte bitte, bis die Mensa-Tabellen geladen sind.'); renderMenuFeedback(card, id); return; } const input = card.querySelector('.sql-input'); const button = card.querySelector('.primary-button'); input.disabled = true; button.disabled = true; try { const actual = await database.exec(check.sql); const expected = await database.exec(referenceSql); const comparison = compareRelations(actual, expected, { columnOrder: true, columnLabels: false, rowOrder: false }); if (comparison.correct) { menuState.results[id] = actual; menuFeedback(id, 'success', options.success || 'Korrekt: Deine Abfrage liefert die erwartete Ergebnisrelation.'); } else { delete menuState.results[id]; const reason = actual.values.length === 0 ? 'Die Anfrage liefert keine Zeilen. Prüfe besonders den Tabellennamen, die Spalte und den Textwert in deiner WHERE-Bedingung.' : comparison.reason; menuFeedback(id, comparison.level === 'partial' ? 'partial' : 'hint', `${comparison.level === 'partial' ? 'Teilweise korrekt' : 'Noch nicht korrekt'}: ${reason}`); } } catch (error) { delete menuState.results[id]; menuFeedback(id, 'error', `SQL-Fehler: ${explainMenuSqlError(error)}`); } input.disabled = false; button.disabled = false; saveMenuState(); renderMenuFeedback(card, id); }
function explainMenuSqlError(error) { const message = String(error?.message || error || ''); if (/no such table/i.test(message)) return 'Prüfe den Tabellennamen. Hier heißen die Tabellen Vorspeise, Hauptspeise und Nachspeise.'; return explainSqlError(error); }
function renderMenuFeedback(card, id) { card.querySelectorAll('.menu-feedback, .menu-sql-result').forEach((node) => node.remove()); const feedback = menuState.feedback[id]; if (feedback) { const box = element('p', `feedback ${feedback.level} menu-feedback`, feedback.text); box.setAttribute('aria-live', 'polite'); card.append(box); } if (menuState.results[id]) { const result = renderMenuResult(menuState.results[id], 'Ergebnisrelation deiner Anfrage'); result.classList.add('menu-sql-result'); card.append(result); } }
async function renderMenuFilter(panel) {
  panel.append(menuHeading(3, 'Anwenden', 'Mit einer Bedingung einschränken'));
  const example = element('section', 'scenario-card accent'); example.append(element('h3', '', 'Nur Menüs mit Salat'), element('p', '', 'Zuerst entsteht das Kreuzprodukt. Die WHERE-Bedingung wählt danach nur die Zeilen mit Salat aus.'), codeBlock("SELECT *\nFROM Vorspeise, Hauptspeise, Nachspeise\nWHERE Vorspeise.name = 'Salat';")); const sampleSlot = element('div', 'sample-menu-result'); sampleSlot.setAttribute('aria-live', 'polite'); example.append(sampleSlot); panel.append(example);
  const task = element('section', 'task-card sql-task'); const prompt = element('p'); prompt.append('Erstelle eine SQL-Abfrage, die ', element('strong', '', 'nur Menüs mit Pizza als Hauptspeise'), ' ausgibt.'); task.append(element('h3', '', 'Deine Anfrage'), prompt); renderMenuSqlInput(task, 'pizza', "SELECT *\nFROM Vorspeise, Hauptspeise, Nachspeise\nWHERE Hauptspeise.name = 'Pizza'", { success: 'Korrekt: Es gibt vier Menüs mit Pizza.', hints: ['Ergänze die vollständige Abfrage um eine WHERE-Bedingung.', 'Da mehrere Tabellen ein Attribut name besitzen, gib auch die Tabelle an: Hauptspeise.name.', "Ergänze zum Gerüst WHERE Hauptspeise.name = '…' den passenden Textwert."] }); panel.append(task);
  const outlook = element('section', 'short-summary'); outlook.append(element('h2', '', 'Vom Filtern zum Verbinden'), element('p', '', "WHERE Vorspeise.name = 'Salat' oder WHERE Hauptspeise.name = 'Pizza' filtert Zeilen nach einem Wert. Bei einem Verbund mit Bedingung werden passende Attribute zweier Tabellen verglichen, zum Beispiel photos.user_id = users.id. Dadurch bleiben nur passende Kombinationen übrig.")); panel.append(outlook);
  if (databaseReady) { try { sampleSlot.append(renderMenuResult(await database.exec("SELECT * FROM Vorspeise, Hauptspeise, Nachspeise WHERE Vorspeise.name = 'Salat'"), 'Ergebnisrelation: Salat-Menüs')); } catch { sampleSlot.append(element('p', 'feedback error', 'Die Beispielanfrage konnte nicht ausgeführt werden.')); } } else sampleSlot.append(element('p', 'feedback hint', 'Die Beispielrelation wird geladen …'));
}
function renderMenuSummary(panel) {
  panel.append(menuHeading(4, 'Sichern und übertragen', 'Zusammenfassung'));
  const summary = element('section', 'short-summary'); summary.append(element('h2', '', 'Das Wichtigste'), listFrom(['Mehrere Tabellen in FROM → Kreuzprodukt.', 'Jeder Datensatz wird mit jedem Datensatz der weiteren Tabellen kombiniert.', 'Anzahl der Ergebniszeilen = Produkt der Anzahlen der Ausgangszeilen.', 'WHERE schränkt die Ergebnisrelation ein.', 'Der Vergleich von Fremd- und Primärschlüssel kann aus dem Kreuzprodukt einen sinnvollen Verbund machen.'])); const results = element('p', 'summary-results', 'Ergebnisse: 4 · 3 · 1 = 12 Menüs; Salat filtert 3 Zeilen; Pizza filtert 4 Zeilen.'); summary.append(results); panel.append(summary);
  const check = element('section', 'task-card'); check.append(element('h3', '', 'Selbstkontrolle'), element('p', '', 'Kreuze alle richtigen Aussagen an.')); const choices = element('div', 'choice-list'); const statements = [['amount', 'Bei 4 Vorspeisen, 3 Hauptspeisen und 1 Nachspeise entstehen 12 Menüs.'], ['from', 'Mehrere Tabellen in FROM ergeben alle möglichen Kombinationen ihrer Datensätze.'], ['where', 'Eine WHERE-Bedingung fügt automatisch neue Menükombinationen hinzu.']]; statements.forEach(([id, text]) => { const label = element('label', 'choice-option'); const input = document.createElement('input'); input.type = 'checkbox'; input.checked = Boolean(menuState.selfCheck[id]); input.addEventListener('change', () => { menuState.selfCheck[id] = input.checked; delete menuState.feedback.selfCheck; saveMenuState(); renderMenuFeedback(check, 'selfCheck'); }); label.append(input, element('span', '', text)); choices.append(label); }); check.append(choices); const button = element('button', 'primary-button', 'Selbstkontrolle prüfen'); button.type = 'button'; button.addEventListener('click', () => { const correct = menuState.selfCheck.amount && menuState.selfCheck.from && !menuState.selfCheck.where; const selectedCorrect = Number(Boolean(menuState.selfCheck.amount)) + Number(Boolean(menuState.selfCheck.from)); if (correct) menuFeedback('selfCheck', 'success', 'Korrekt: Du hast Anzahl, FROM und WHERE richtig eingeordnet.'); else if (selectedCorrect) menuFeedback('selfCheck', 'partial', 'Teilweise korrekt: Prüfe besonders, ob WHERE Zeilen auswählt oder neue Kombinationen erzeugt.'); else menuFeedback('selfCheck', 'hint', 'Noch nicht korrekt. Denke an die Anzahl der Kombinationen und daran, was WHERE mit einer Ergebnisrelation macht.'); renderMenuFeedback(check, 'selfCheck'); }); check.append(button); renderMenuFeedback(check, 'selfCheck'); panel.append(check);
}
function listFrom(lines) { const list = document.createElement('ul'); lines.forEach((line) => list.append(element('li', '', line))); return list; }
async function initMenuCrossProduct() { restoreMenuState(); renderMenuModule(); const status = document.getElementById('data-status'); try { database = new SqlWorker(); await database.init({ mode: 'menu-cross-product' }); databaseReady = true; status.textContent = 'Die drei Mensa-Tabellen sind geladen. Du kannst SQL-Anfragen ausführen.'; status.className = 'feedback success'; status.setAttribute('aria-busy', 'false'); renderMenuModule(); } catch (error) { status.textContent = 'Die Mensa-Tabellen konnten nicht geladen werden. Bitte lade die Seite neu.'; status.className = 'feedback error'; status.setAttribute('aria-busy', 'false'); console.error(error); } document.getElementById('reset-module').addEventListener('click', () => { if (window.confirm('Möchtest du alle Eingaben und den Fortschritt dieser Aufgabe zurücksetzen?')) { localStorage.removeItem(MENU_STORAGE_KEY); location.reload(); } }); window.addEventListener('beforeunload', () => database?.close()); }

// Aufgabe 7 baut den Verbund in zwei prüfbaren Schritten aus derselben SQL-Datenbank auf.
const VERBUND_STORAGE_KEY = 'inf10-song-verbund-v1';
const VERBUND_TABS = [['source', 'Ausgangstabellen'], ['cross', '32 Kombinationen'], ['first', 'Erste Verbindung'], ['second', 'Zweite Verbindung'], ['sql', 'SQL-Anfrage'], ['check', 'Sicherung']];
const verbundState = { tab: 'source', mapping: '', prediction: '', crossExecuted: false, crossClass: {}, firstColumns: [], secondColumns: [], operator: '', answers: {}, results: {}, feedback: {}, check: {}, completed: {}, summaryUnlocked: false };
function saveVerbundState() { localStorage.setItem(VERBUND_STORAGE_KEY, JSON.stringify(verbundState)); }
function restoreVerbundState() { try { Object.assign(verbundState, JSON.parse(localStorage.getItem(VERBUND_STORAGE_KEY) || '{}')); } catch { /* Speicherstand ist optional. */ } }
function verbundFeedback(id, level, text) { verbundState.feedback[id] = { level, text }; saveVerbundState(); }
function verbundDone(id) { return Boolean(verbundState.completed[id]); }
function crossDone() { return verbundState.prediction === '32' && verbundState.crossExecuted && verbundState.crossClass.good === 'passend' && verbundState.crossClass.song === 'unpassend' && verbundState.crossClass.playlist === 'unpassend'; }
function availableVerbundTab(id) { if (id === 'source') return true; if (id === 'cross') return verbundDone('source'); if (id === 'first') return crossDone(); if (id === 'second') return verbundDone('first'); if (id === 'sql') return verbundDone('second'); if (id === 'check') return verbundDone('sql'); return false; }
function completeVerbund(id) { verbundState.completed[id] = true; saveVerbundState(); }
function activateVerbundTab(id, { focusContent = false } = {}) { const allowed = id === 'summary' ? verbundState.summaryUnlocked : availableVerbundTab(id); if (!allowed) return; verbundState.tab = id; saveVerbundState(); renderVerbundModule({ focusContent }); }
function renderVerbundModule({ focusContent = false } = {}) {
  if (!availableVerbundTab(verbundState.tab) && verbundState.tab !== 'summary') verbundState.tab = 'source';
  if (verbundState.tab === 'summary' && !verbundState.summaryUnlocked) verbundState.tab = 'source';
  const labels = verbundState.summaryUnlocked ? [...VERBUND_TABS, ['summary', 'Übersicht']] : VERBUND_TABS;
  const progress = document.getElementById('verbund-progress'); if (progress) progress.textContent = verbundState.tab === 'summary' ? 'Übersicht freigeschaltet' : `Schritt ${Math.max(1, VERBUND_TABS.findIndex(([id]) => id === verbundState.tab) + 1)} von 6`;
  const tabs = document.getElementById('verbund-tabs'); tabs.replaceChildren();
  labels.forEach(([id, label], index) => { const button = element('button', 'step-tab', label); button.type = 'button'; button.id = `tab-${id}`; button.dataset.tab = id; button.role = 'tab'; button.ariaSelected = String(verbundState.tab === id); button.tabIndex = verbundState.tab === id ? 0 : -1; const allowed = id === 'summary' ? verbundState.summaryUnlocked : availableVerbundTab(id); button.disabled = !allowed; if (verbundDone(id)) button.classList.add('is-complete'); button.setAttribute('aria-controls', 'verbund-panel'); button.addEventListener('click', () => activateVerbundTab(id)); button.addEventListener('keydown', (event) => moveTabFocus(event, labels.filter(([tab]) => tab === 'summary' || availableVerbundTab(tab)), Math.max(0, labels.filter(([tab]) => tab === 'summary' || availableVerbundTab(tab)).findIndex(([tab]) => tab === id)))); tabs.append(button); });
  const panel = document.getElementById('verbund-panel'); panel.replaceChildren(); panel.setAttribute('aria-labelledby', `tab-${verbundState.tab}`);
  panel.append(schemaCard(SONG_VERBUND_TABLE_SCHEMAS));
  if (verbundState.tab === 'source') renderVerbundSource(panel); if (verbundState.tab === 'cross') renderVerbundCross(panel); if (verbundState.tab === 'first') renderVerbundFirst(panel); if (verbundState.tab === 'second') renderVerbundSecond(panel); if (verbundState.tab === 'sql') renderVerbundSql(panel); if (verbundState.tab === 'check') renderVerbundCheck(panel); if (verbundState.tab === 'summary') renderVerbundSummary(panel);
  renderTabFlowNavigation(panel, { items: labels.map(([id, label]) => ({ id, label })), currentId: verbundState.tab, onNavigate: activateVerbundTab, isEnabled: (id) => id === 'summary' ? verbundState.summaryUnlocked : availableVerbundTab(id) });
  syncTabSemantics(tabs, verbundState.tab);
  if (focusContent) focusTabPanelStart(panel);
}
function verbundHeading(number, kicker, title) { const heading = element('div', 'step-heading'); heading.append(element('span', 'step-number', String(number))); const copy = element('div'); copy.append(element('p', 'step-kicker', kicker), element('h2', '', title)); heading.append(copy); return heading; }
function appendVerbundFeedback(card, id) { const feedback = verbundState.feedback[id]; if (!feedback) return; const box = element('p', `feedback ${feedback.level}`, feedback.text); box.setAttribute('aria-live', 'polite'); card.append(box); }
function renderSongSourceTables(options = {}) {
  const wrapper = element('div', 'song-source-tables');
  SONG_VERBUND_COLUMN_GROUPS.forEach(({ table: tableName, columns }) => { const section = element('section', 'table-shell song-source-table'); const scroll = element('div', 'table-scroll'); scroll.tabIndex = 0; scroll.setAttribute('aria-label', `Tabelle ${tableName} horizontal scrollen`); const table = document.createElement('table'); table.append(element('caption', '', tableName)); const head = document.createElement('thead'); const tr = document.createElement('tr'); columns.forEach((column) => { const qualified = `${tableName}.${column}`; const keyText = qualified === 'Song.id' || qualified === 'Playlist.id' ? 'PK – Primärschlüssel' : qualified === 'Song_in_Playlist.song_id' ? 'FK → Song.id' : qualified === 'Song_in_Playlist.playlist_id' ? 'FK → Playlist.id' : ''; const th = document.createElement('th'); th.scope = 'col'; if (options.selectable) { const button = element('button', 'column-selector', column); button.type = 'button'; button.dataset.column = qualified; button.setAttribute('aria-pressed', String(options.selected.includes(qualified))); button.setAttribute('aria-label', `Spalte ${qualified} auswählen`); button.addEventListener('click', () => options.onSelect(qualified)); th.append(button); } else th.append(element('span', '', column)); if (keyText) th.append(element('small', 'key-label', keyText)); tr.append(th); }); head.append(tr); const body = document.createElement('tbody'); SONG_VERBUND_TABLES[tableName].forEach((row) => { const line = document.createElement('tr'); columns.forEach((column) => line.append(element('td', '', String(row[column])))); body.append(line); }); table.append(head, body); scroll.append(table); section.append(scroll); wrapper.append(section); }); return wrapper;
}
function renderVerbundSource(panel) {
  panel.append(verbundHeading(1, 'Entdecken', 'Ausgangstabellen')); const scenario = element('section', 'scenario-card accent'); scenario.append(element('h3', '', 'Welche Songs gehören zu welcher Playlist?'), element('p', '', 'Betrachte zuerst die drei Tabellen und ihre Schlüssel.')); scenario.append(renderSongSourceTables()); panel.append(scenario);
  const task = element('section', 'task-card'); task.append(element('h3', '', 'Zuordnungstabelle finden'), element('p', '', 'Welche Tabelle speichert die Zuordnungen von Songs zu Playlists?')); const choices = element('div', 'choice-list'); SONG_VERBUND_TABLE_NAMES.forEach((name) => { const label = element('label', 'choice-option'); const input = document.createElement('input'); input.type = 'radio'; input.name = 'verbund-mapping'; input.value = name; input.checked = verbundState.mapping === name; input.addEventListener('change', () => { verbundState.mapping = name; delete verbundState.feedback.mapping; task.querySelector('.feedback')?.remove(); saveVerbundState(); }); label.append(input, element('span', '', name)); choices.append(label); }); const button = element('button', 'primary-button', 'Auswahl prüfen'); button.type = 'button'; button.addEventListener('click', () => { if (verbundState.mapping === 'Song_in_Playlist') { completeVerbund('source'); verbundFeedback('mapping', 'success', 'Korrekt: Song_in_Playlist enthält jeweils die Nummer eines Songs und einer Playlist. Schritt 2 ist freigeschaltet.'); } else verbundFeedback('mapping', 'hint', 'Noch nicht korrekt. Suche die Tabelle, die zwei Fremdschlüssel enthält.'); renderVerbundModule(); }); task.append(choices, button); appendVerbundFeedback(task, 'mapping'); panel.append(task);
}
function renderVerbundCross(panel) {
  panel.append(verbundHeading(2, 'Beobachten', '32 Kombinationen')); const task = element('section', 'task-card sql-task'); task.append(element('h3', '', 'Vorhersage'), element('p', '', 'Wie viele Zeilen entstehen ohne Bedingung aus 4 Songs, 4 Zuordnungszeilen und 2 Playlists?')); const label = element('label', 'sql-label', 'Erwartete Anzahl der Zeilen'); label.htmlFor = 'verbund-prediction'; const input = document.createElement('input'); input.id = label.htmlFor; input.type = 'number'; input.inputMode = 'numeric'; input.min = '0'; input.className = 'menu-number-input'; input.value = verbundState.prediction; input.addEventListener('input', () => { verbundState.prediction = input.value; delete verbundState.feedback.prediction; task.querySelector('.feedback')?.remove(); saveVerbundState(); }); const button = element('button', 'primary-button', 'Anzahl prüfen'); button.type = 'button'; button.addEventListener('click', () => { if (Number(verbundState.prediction) === 32) { verbundState.prediction = '32'; verbundFeedback('prediction', 'success', 'Korrekt: 4 · 4 · 2 = 32 Kombinationen.'); } else verbundFeedback('prediction', 'hint', 'Noch nicht korrekt. Multipliziere die Anzahl der Zeilen aller drei Tabellen.'); renderVerbundModule(); }); task.append(label, input, button); appendVerbundFeedback(task, 'prediction'); panel.append(task);
  if (verbundState.prediction === '32') { const resultCard = element('section', 'task-card'); resultCard.append(element('h3', '', 'Kreuzprodukt ausführen'), element('p', '', 'Führe die Abfrage aus. Sie verbindet zunächst jede Zeile mit jeder anderen Zeile.')); resultCard.append(codeBlock(SONG_VERBUND_SQL.crossProduct)); const run = element('button', 'primary-button', '32 Kombinationen anzeigen'); run.type = 'button'; run.disabled = !databaseReady; run.addEventListener('click', async () => { try { verbundState.results.cross = await database.exec(SONG_VERBUND_SQL.crossProduct); verbundState.crossExecuted = true; verbundFeedback('cross-run', 'success', 'Die SQL-Abfrage liefert 32 Kombinationen.'); saveVerbundState(); renderVerbundModule(); } catch (error) { verbundFeedback('cross-run', 'error', `SQL-Fehler: ${explainSqlError(error)}`); renderVerbundModule(); } }); resultCard.append(run); appendVerbundFeedback(resultCard, 'cross-run'); if (verbundState.results.cross) resultCard.append(renderSongRelation(verbundState.results.cross, 'Ergebnisrelation: 32 Kombinationen')); panel.append(resultCard); }
  if (verbundState.crossExecuted) { const classify = element('section', 'task-card'); classify.append(element('h3', '', 'Drei Kombinationen beurteilen'), element('p', '', 'Ist die dargestellte Zuordnung fachlich passend?')); const examples = [['good', 'Gaslighter – Zuordnung 1 / 1 – Good Oldies', 'passend'], ['song', 'Gaslighter – Zuordnung 2 / 2 – Fussballhits', 'unpassend'], ['playlist', 'Try – Zuordnung 3 / 1 – Fussballhits', 'unpassend']]; examples.forEach(([id, text]) => { const group = element('fieldset', 'verbund-classify'); group.append(element('legend', '', text)); ['passend', 'unpassend'].forEach((value) => { const label = element('label', 'choice-option'); const radio = document.createElement('input'); radio.type = 'radio'; radio.name = `cross-${id}`; radio.value = value; radio.checked = verbundState.crossClass[id] === value; radio.addEventListener('change', () => { verbundState.crossClass[id] = value; delete verbundState.feedback.classify; classify.querySelector('.feedback')?.remove(); saveVerbundState(); }); label.append(radio, element('span', '', value)); group.append(label); }); classify.append(group); }); const check = element('button', 'primary-button', 'Beurteilungen prüfen'); check.type = 'button'; check.addEventListener('click', () => { if (crossDone()) { completeVerbund('cross'); verbundFeedback('classify', 'success', 'Korrekt: Bei Gaslighter passt Song.id 1 nicht zu Song_in_Playlist.song_id 2. Bei Try passt Song_in_Playlist.playlist_id 1 nicht zu Playlist.id 2.'); } else verbundFeedback('classify', 'hint', 'Noch nicht korrekt. Gaslighter gehört zur Zuordnungszeile 1 / 1; Try gehört nicht zu Fussballhits.'); renderVerbundModule(); }); classify.append(check); appendVerbundFeedback(classify, 'classify'); panel.append(classify); }
}
function toggleVerbundColumn(property, column) { const selected = verbundState[property]; verbundState[property] = selected.includes(column) ? selected.filter((item) => item !== column) : selected.length < 2 ? [...selected, column] : [selected[1], column]; delete verbundState.feedback[property]; saveVerbundState(); renderVerbundModule(); }
function renderSongRelation(relation, title) { const output = renderRelation(relation, { title, caption: title, columns: SONG_VERBUND_COLUMNS, columnGroups: SONG_VERBUND_COLUMN_GROUPS }); output.classList.add('verbund-result'); return output; }
function renderVerbundFirst(panel) {
  panel.append(verbundHeading(3, 'Verstehen', 'Erste Verbindung')); const card = element('section', 'task-card'); card.append(element('h3', '', 'Passende Song-Nummern verbinden'), element('p', '', 'Wähle genau die zwei Spalten, deren Werte dieselbe Song-Nummer meinen.')); card.append(renderSongSourceTables({ selectable: true, selected: verbundState.firstColumns, onSelect: (column) => toggleVerbundColumn('firstColumns', column) })); card.append(element('p', 'selected-columns', verbundState.firstColumns.length ? `Gewählt: ${verbundState.firstColumns.join(' = ')}` : 'Noch keine zwei Spalten gewählt.')); appendHints(card, SONG_VERBUND_VISIBLE_TEXT.firstHints); const button = element('button', 'primary-button', 'Verbindung prüfen'); button.type = 'button'; button.addEventListener('click', async () => { if (!evaluateFirstConnection(verbundState.firstColumns)) { verbundFeedback('firstColumns', 'hint', 'Noch nicht korrekt. Ein Primärschlüssel aus Song muss zu dem Fremdschlüssel passen, der auf ihn zeigt.'); renderVerbundModule(); return; } try { verbundState.results.first = await database.exec(SONG_VERBUND_SQL.firstConnection); completeVerbund('first'); verbundFeedback('firstColumns', 'success', 'Korrekt: Die erste Bedingung lässt 8 Zeilen übrig. Jede passende Song-Zuordnung wird aber noch mit beiden Playlists kombiniert.'); saveVerbundState(); renderVerbundModule(); } catch (error) { verbundFeedback('firstColumns', 'error', `SQL-Fehler: ${explainSqlError(error)}`); renderVerbundModule(); } }); card.append(button); appendVerbundFeedback(card, 'firstColumns'); if (verbundState.results.first) card.append(renderSongRelation(verbundState.results.first, 'Ergebnisrelation: erste Verbindung (8 Zeilen)')); panel.append(card);
}
function renderVerbundSecond(panel) {
  panel.append(verbundHeading(4, 'Anwenden', 'Zweite Verbindung')); const card = element('section', 'task-card'); card.append(element('h3', '', 'Auch die Playlist passend verbinden'), element('p', '', 'Die erste Bedingung steht fest. Wähle die zweite Spaltenverbindung und die passende Verknüpfung.')); card.append(codeBlock('Song.id = Song_in_Playlist.song_id')); const operators = element('div', 'choice-list'); ['AND', 'OR'].forEach((operator) => { const label = element('label', 'choice-option'); const radio = document.createElement('input'); radio.type = 'radio'; radio.name = 'verbund-operator'; radio.value = operator; radio.checked = verbundState.operator === operator; radio.addEventListener('change', () => { verbundState.operator = operator; delete verbundState.feedback.secondColumns; card.querySelector('.feedback')?.remove(); saveVerbundState(); }); label.append(radio, element('span', '', operator)); operators.append(label); }); card.append(operators, renderSongSourceTables({ selectable: true, selected: verbundState.secondColumns, onSelect: (column) => toggleVerbundColumn('secondColumns', column) }), element('p', 'selected-columns', verbundState.secondColumns.length ? `Gewählt: ${verbundState.secondColumns.join(' = ')}` : 'Noch keine zwei Spalten gewählt.')); appendHints(card, SONG_VERBUND_VISIBLE_TEXT.secondHints); const button = element('button', 'primary-button', 'Vollständigen Verbund prüfen'); button.type = 'button'; button.addEventListener('click', async () => { if (!evaluateSecondConnection(verbundState.secondColumns, verbundState.operator)) { const text = verbundState.operator === 'OR' ? 'Noch nicht korrekt: Mit OR genügt schon eine Bedingung; beide Verbindungen müssen gleichzeitig stimmen.' : 'Noch nicht korrekt. Verbinde Playlist.id mit dem passenden Fremdschlüssel und wähle AND.'; verbundFeedback('secondColumns', 'hint', text); renderVerbundModule(); return; } try { verbundState.results.second = await database.exec(SONG_VERBUND_SQL.fullConnection); completeVerbund('second'); verbundFeedback('secondColumns', 'success', 'Korrekt: Jetzt bleiben genau 4 sinnvolle Song-Playlist-Zuordnungen.'); saveVerbundState(); renderVerbundModule(); } catch (error) { verbundFeedback('secondColumns', 'error', `SQL-Fehler: ${explainSqlError(error)}`); renderVerbundModule(); } }); card.append(button); appendVerbundFeedback(card, 'secondColumns'); if (verbundState.results.second) { card.append(renderSongRelation(verbundState.results.second, 'Ergebnisrelation: vollständiger Verbund (4 Zeilen)')); card.append(renderPairList()); } panel.append(card);
}
function renderPairList() { const section = element('section', 'short-summary'); section.append(element('h3', '', 'Die vier passenden Paare')); const list = document.createElement('ul'); SONG_PLAYLIST_PAIRS.forEach(({ song, playlist }) => list.append(element('li', '', `${song} → ${playlist}`))); section.append(list); return section; }
function renderVerbundSql(panel) {
  panel.append(verbundHeading(5, 'Übertragen', 'SQL-Anfrage')); const card = element('section', 'task-card sql-task'); card.append(element('h3', '', 'Vollständigen Verbund selbst formulieren'), element('p', '', 'Schreibe eine SELECT-Anfrage, die genau die vier passenden Song-Playlist-Zuordnungen ausgibt.')); const label = element('label', 'sql-label', 'Deine vollständige SQL-Anweisung'); label.htmlFor = 'verbund-sql-input'; const input = document.createElement('textarea'); input.id = label.htmlFor; input.className = 'sql-input'; input.spellcheck = false; input.placeholder = NEUTRAL_SQL_PLACEHOLDER; input.value = verbundState.answers.sql || ''; input.addEventListener('input', () => { verbundState.answers.sql = input.value; delete verbundState.feedback.sql; delete verbundState.results.sql; card.querySelector('.feedback')?.remove(); card.querySelector('.verbund-result')?.remove(); saveVerbundState(); }); input.addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') { event.preventDefault(); runVerbundSql(); } }); card.append(label, input); appendHints(card, SONG_VERBUND_VISIBLE_TEXT.sqlHints); const run = element('button', 'primary-button', 'SQL-Anfrage prüfen'); run.type = 'button'; run.disabled = !databaseReady; run.addEventListener('click', runVerbundSql); card.append(run, element('span', 'shortcut-hint', 'Strg/Cmd + Enter')); appendVerbundFeedback(card, 'sql'); if (verbundState.results.sql) card.append(renderSongRelation(verbundState.results.sql, 'Ergebnisrelation deiner Anfrage (4 Zeilen)')); panel.append(card);
}
async function runVerbundSql() { const checked = validateSelectStatement(verbundState.answers.sql || ''); if (!checked.ok) { verbundFeedback('sql', 'hint', checked.message); renderVerbundModule(); return; } try { const actual = await database.exec(checked.sql); const expected = await database.exec(SONG_VERBUND_SQL.fullConnection); const comparison = compareRelations(actual, expected, { columnOrder: true, columnLabels: false, rowOrder: false }); if (comparison.correct) { verbundState.results.sql = actual; completeVerbund('sql'); verbundFeedback('sql', 'success', 'Korrekt: Deine Anfrage liefert genau die vier passenden Zuordnungen.'); } else { delete verbundState.results.sql; const amount = actual.values.length; const text = amount === 8 ? 'Teilweise korrekt: Die Verbindung zur Playlist fehlt noch; deshalb bleiben 8 Zeilen.' : amount === 16 ? 'Teilweise korrekt: Die Verbindung zum Song fehlt noch; deshalb bleiben 16 Zeilen.' : amount === 20 ? 'Noch nicht korrekt: OR lässt Zeilen zu, bei denen nur eine Bedingung stimmt. Verwende AND.' : amount === 32 ? 'Noch nicht korrekt: Die WHERE-Bedingungen fehlen noch; das ist das Kreuzprodukt.' : amount === 0 ? 'Noch nicht korrekt: Die Bedingungen liefern keine Zeilen. Prüfe die beiden Schlüsselpaare.' : `Noch nicht korrekt: ${comparison.reason}`; verbundFeedback('sql', amount === 8 || amount === 16 ? 'partial' : 'hint', text); } saveVerbundState(); renderVerbundModule(); } catch (error) { verbundFeedback('sql', 'error', `SQL-Fehler: ${explainSongSqlError(error)}`); renderVerbundModule(); } }
function explainSongSqlError(error) { const message = String(error?.message || error || ''); if (/no such table/i.test(message)) return 'Prüfe den Tabellennamen. Hier heißen die Tabellen Song, Song_in_Playlist und Playlist.'; return explainSqlError(error); }
function renderVerbundCheck(panel) {
  panel.append(verbundHeading(6, 'Sichern', 'Selbstkontrolle')); const card = element('section', 'task-card'); card.append(element('h3', '', 'Vier Aussagen prüfen'), element('p', '', 'Wähle für jede Aussage die richtige Ergänzung.')); const questions = [['song', 'Welche erste Gleichung verbindet Song und Song_in_Playlist?', 'Song.id = Song_in_Playlist.song_id', 'Song.id = Playlist.id'], ['playlist', 'Welche zweite Gleichung verbindet Playlist und Song_in_Playlist?', 'Playlist.id = Song_in_Playlist.playlist_id', 'Playlist.titel = Song.titel'], ['and', 'Wie werden beide Bedingungen verbunden?', 'AND', 'OR'], ['count', 'Wie viele Tabellen und Verbindungen sind beteiligt?', '3 Tabellen und 2 Verbindungen', '2 Tabellen und 3 Verbindungen']]; questions.forEach(([id, prompt, correct, wrong]) => { const group = element('fieldset', 'verbund-classify'); group.append(element('legend', '', prompt)); [correct, wrong].forEach((answer) => { const label = element('label', 'choice-option'); const radio = document.createElement('input'); radio.type = 'radio'; radio.name = `check-${id}`; radio.value = answer; radio.checked = verbundState.check[id] === answer; radio.addEventListener('change', () => { verbundState.check[id] = answer; delete verbundState.feedback.check; card.querySelector('.feedback')?.remove(); saveVerbundState(); }); label.append(radio, element('span', '', answer)); group.append(label); }); card.append(group); }); const button = element('button', 'primary-button', 'Selbstkontrolle prüfen'); button.type = 'button'; button.addEventListener('click', () => { const correct = questions.filter(([id, , answer]) => verbundState.check[id] === answer).length; if (correct === questions.length) { completeVerbund('check'); verbundState.summaryUnlocked = true; verbundFeedback('check', 'success', 'Korrekt: Du hast beide Schlüsselverbindungen, AND und die Struktur des Verbunds eingeordnet. Die Übersicht ist freigeschaltet.'); } else if (correct) verbundFeedback('check', 'partial', `Teilweise korrekt: ${correct} von 4 Antworten stimmen. Prüfe die noch offenen Schlüsselpaare und AND.`); else verbundFeedback('check', 'hint', 'Noch nicht korrekt. Nimm die drei Ausgangstabellen und die zwei Gleichheitsbedingungen als Hilfe.'); saveVerbundState(); renderVerbundModule(); }); card.append(button); appendVerbundFeedback(card, 'check'); panel.append(card);
}
function renderVerbundSummary(panel) {
  panel.append(verbundHeading(7, 'Zusammenfassen', 'Übersicht')); const card = element('section', 'short-summary'); card.append(element('h2', '', 'Der Weg zum Verbund')); card.append(listFrom(['Ausgangsfrage: Welche Songs gehören zu welcher Playlist? Die Zuordnungstabelle heißt Song_in_Playlist.', 'Kreuzprodukt: 4 · 4 · 2 = 32 Kombinationen.', 'Erste Verbindung: Song.id = Song_in_Playlist.song_id → 8 Zeilen.', 'Zweite Verbindung: Playlist.id = Song_in_Playlist.playlist_id und AND → 4 Zeilen.', 'Struktur: 3 Tabellen und 2 Verbindungen.'])); card.append(element('h3', '', 'Vollständige Anfrage'), codeBlock(SONG_VERBUND_SQL.fullConnection)); const memory = element('section', 'short-summary verbund-memory'); memory.append(element('h3', '', 'Merksatz'), element('p', '', SONG_VERBUND_VISIBLE_TEXT.memory)); card.append(memory, renderPairList()); panel.append(card);
}
async function initSongVerbund() { restoreVerbundState(); renderVerbundModule(); const status = document.getElementById('data-status'); try { database = new SqlWorker(); await database.init({ mode: 'song-verbund' }); databaseReady = true; status.textContent = 'Die drei Song-Tabellen sind geladen. Du kannst SQL-Anfragen ausführen.'; status.className = 'feedback success'; status.setAttribute('aria-busy', 'false'); renderVerbundModule(); } catch (error) { status.textContent = 'Die Song-Tabellen konnten nicht geladen werden. Bitte lade die Seite neu.'; status.className = 'feedback error'; status.setAttribute('aria-busy', 'false'); console.error(error); } document.getElementById('reset-module').addEventListener('click', () => { if (window.confirm('Möchtest du alle Eingaben und den Fortschritt dieser Aufgabe zurücksetzen?')) { localStorage.removeItem(VERBUND_STORAGE_KEY); location.reload(); } }); window.addEventListener('beforeunload', () => database?.close()); }

async function init() { restore(); render(); const status = document.getElementById('data-status'); try { database = new SqlWorker(); await database.init(); databaseReady = true; status.textContent = 'Die Tabelle users ist geladen. Du kannst SQL-Anfragen ausführen.'; status.className = 'feedback success'; status.setAttribute('aria-busy', 'false'); render(); } catch (error) { status.textContent = 'Die Übungsdaten konnten nicht geladen werden. Bitte lade die Seite neu.'; status.className = 'feedback error'; status.setAttribute('aria-busy', 'false'); console.error(error); document.querySelectorAll('.sql-input, .sql-task button').forEach((node) => { node.disabled = true; }); } document.getElementById('reset-module').addEventListener('click', () => { if (window.confirm('Möchtest du alle SQL-Eingaben und den Fortschritt dieser Aufgabe zurücksetzen?')) { localStorage.removeItem(STORAGE_KEY); location.reload(); } }); window.addEventListener('beforeunload', () => database?.close()); }
document.addEventListener('DOMContentLoaded', () => document.body.dataset.sqlModule === 'menu-cross-product' ? initMenuCrossProduct() : document.body.dataset.sqlModule === 'song-verbund' ? initSongVerbund() : init());
