import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';

const html = readFileSync(new URL('../../aufgabe5.html', import.meta.url), 'utf8');
const csv = readFileSync(new URL('../data/Trainingsdaten_Tiere.csv', import.meta.url));
const ui = readFileSync(new URL('../ui/task5.mjs', import.meta.url), 'utf8');
assert.match(html, /id="final-quiz"/);
assert.match(html, /role="tablist"/);
assert.match(html, /target="_blank" rel="noopener noreferrer"/);
assert.match(html, /„Geometrische Darstellung“/);
assert.doesNotMatch(html, /„Geometrische Ansicht“/);
assert.match(html, /data-answer="correctPoints"/);
assert.match(html, /data-answer="lineW1"/);
assert.match(html, /data-answer="lineW2"/);
assert.match(html, /100&nbsp;% gelten nur für diese bekannten Beispiele/);
assert.match(html, /Trefferquote auf Trainingsdaten/);
assert.match(html, /class="wool-links"/);
assert.match(html, /blaue Klammern/);
assert.match(html, /rote Klammern/);
assert.match(html, /class="structure-links"/);
assert.match(html, /class="model-lines-scroll" role="region"[^>]*tabindex="0"/);
assert.match(html, /Schwellenwert θ/);
assert.match(html, /Aktivierungsfunktion f/);
assert.doesNotMatch(readFileSync(new URL('../task5.css', import.meta.url), 'utf8'), /model-lines::before/);
assert.match(readFileSync(new URL('../task5.css', import.meta.url), 'utf8'), /input:not\(\[type="checkbox"\]\)/);
assert.match(ui, /data-correct=/);
assert.match(ui, /showStep\(STEPS\[next\]\); document\.querySelector\(`\[data-tab=\$\{STEPS\[next\]\}\]`\)\?\.focus\(\)/);
assert.match(ui, /index === epoch\.length - 1 \? 'Korrekt\. Nach vier Schritten gilt w₁ = −3, w₂ = 4 und θ = 1\./);
assert.match(ui, /options\.filter\(\(option\)=>option\.correct\)\.map\(\(option\)=>option\.id\)/);
assert.match(ui, /id:'threshold'[\s\S]*id:'inputs'[\s\S]*id:'output-change'[\s\S]*id:'weights'/);
assert.match(ui, /id:'class'[\s\S]*id:'sum'[\s\S]*id:'output'[\s\S]*id:'negative'/);
assert.match(ui, /id:'delta'[\s\S]*id:'all-smaller'[\s\S]*id:'threshold-rule'[\s\S]*id:'zero'/);
assert.match(ui, /id:'remaining-error'[\s\S]*id:'final'[\s\S]*id:'step-three'[\s\S]*id:'step-two'/);
assert.match(ui, /id:'normal'[\s\S]*id:'line'[\s\S]*id:'rate'[\s\S]*id:'linear'/);
assert.match(ui, /id:'compare'[\s\S]*id:'goal'[\s\S]*id:'no-consciousness'[\s\S]*id:'algorithm'/);
assert.doesNotMatch(html, /<iframe/i);
assert.doesNotMatch(html, /Wollperzeptron \(vollständig\)|Einführungspräsentation|AB-Lsg-Das-Perzeptron/);
assert.equal(statSync(new URL('../data/Trainingsdaten_Tiere.csv', import.meta.url)).size, 59);
assert.equal(csv.toString('utf8'), 'Zahnlänge;Augengröße;Label\r\n2;2;1\r\n4;1;0\r\n6;2;0\r\n0;4;1\r\n');
assert.equal(createHash('sha256').update(csv).digest('hex').toUpperCase(), '107FE6A36A27F691F41221FF53D6BF34815846AEF88B8D7B7182E5AB16A449A6');
console.log('HTML-Vertrag und bytegenaue Trainingsdaten sind korrekt.');
