import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';

const html = readFileSync(new URL('../../aufgabe5.html', import.meta.url), 'utf8');
const css = readFileSync(new URL('../task5.css', import.meta.url), 'utf8');
const ui = readFileSync(new URL('../ui/task5.mjs', import.meta.url), 'utf8');
const csv = readFileSync(new URL('../data/Trainingsdaten_Tiere.csv', import.meta.url));

assert.equal((html.match(/role="tab"/g) || []).length, 8);
for (const id of ['discover','structure','decide','learn','simulator','fast','limits','summary']) assert.match(html, new RegExp('data-tab="' + id + '"'));
assert.match(html, /Vom Tier zur Entscheidung/);
assert.match(html, /So rechnet das Perzeptron/);
assert.match(html, /Ein Hai wird klassifiziert/);
assert.match(html, /Hase \(2\|4\)/);
assert.match(html, /−3x₁ \+ 4x₂ = 1/);
assert.match(html, /x₁: Zahnlänge/);
assert.match(html, /x₂: Augengröße/);
assert.match(html, /safe-pattern/);
assert.match(html, /danger-pattern/);
assert.match(html, /class="signal-flow"/);
assert.match(html, /data-signal-step="6"/);
assert.match(html, /data-signal-arrow="activation output"/);
assert.match(html, /Das Zahlenbeispiel verwendet andere Gewichte als die Trenngerade/);
assert.match(html, /Ein Perzeptron multipliziert Eingaben mit Gewichten, addiert die Ergebnisse und vergleicht die Summe mit einem Schwellenwert\./);
assert.match(html, /data-answer="product1"/);
assert.match(html, /id="final-quiz"/);
assert.match(html, /target="_blank" rel="noopener noreferrer"/);
assert.doesNotMatch(html + css + ui, /wool|Wollperzeptron|blaue Klammern|rote Klammern|clip-mark|term-palette|term-targets/i);
assert.doesNotMatch(html, /Wollperzeptron \(vollständig\)|Einführungspräsentation|AB-Lsg-Das-Perzeptron/);
assert.match(ui, /geometryStep/);
assert.match(ui, /signalStep/);
assert.match(ui, /data-signal-arrow/);
assert.match(ui, /product1:-4,product2:2,sum:-2,comparison:'lt',output:'0',class:'danger'/);
assert.match(ui, /a ≥ θ den Wert 1 aus, sonst 0/);
assert.match(css, /@media \(max-width:700px\)/);
assert.match(css, /signal-node:not\(:last-child\)::after/);
assert.equal(statSync(new URL('../data/Trainingsdaten_Tiere.csv', import.meta.url)).size, 59);
assert.equal(csv.toString('utf8'), 'Zahnlänge;Augengröße;Label\r\n2;2;1\r\n4;1;0\r\n6;2;0\r\n0;4;1\r\n');
assert.equal(createHash('sha256').update(csv).digest('hex').toUpperCase(), '107FE6A36A27F691F41221FF53D6BF34815846AEF88B8D7B7182E5AB16A449A6');
console.log('HTML-Vertrag, Interaktionen und bytegenaue Trainingsdaten sind korrekt.');
